import { ScenarioKnowledgeItem } from '../types/scenarioKnowledge';

export const SCENARIO_DATA_PART_2: ScenarioKnowledgeItem[] = [
  {
    id: 'SCN_031',
    numeric_id: 31,
    title_ar: 'طهارة الكلب وثياب المصلي عند الملامسة الجافة أو الرطبة',
    title_en: 'Dog Contact and Purity of Prayer Clothes',
    topic: 'purity',
    unique_user_intent: 'purity_dog_contact_garments',
    contexts: ['street', 'park', 'home'],
    learning_objective_ar: 'التمييز بين الملامسة الجافة ولعاب الكلب وتطهير ما أصابه اللعاب',
    learning_objective_en: 'Distinguish dry contact from saliva; purify only items contacted by dog saliva',
    difficulty: 'beginner',
    interaction_engine: 'inspection',
    keywords_ar: ['لمس الكلب', 'لعاب الكلب', 'ملابس الصلاة والكلاب', 'طهارة الثوب'],
    keywords_en: ['dog saliva', 'dog contact', 'purity clothes dog', 'dog petting'],
    approved_sources: [
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'صحيح مسلم — حديث أبي هريرة رضي الله عنه في ولوغ الكلب',
        source_page_url: 'https://dorar.net/hadith/sharh/2790',
        verbatim_evidence_text: '«طهور إناء أحدكم إذا ولغ فيه الكلب أن يغسله سبع مرات، أولاهن بالتراب»',
      },
      {
        registry_source_id: 'dorar_fiqh',
        reference_title: 'الموسوعة الفقهية — حكم ملامسة شعر الكلب الجاف للصلاة',
        source_page_url: 'https://dorar.net/feqhia/298',
        verbatim_evidence_text: 'ملامسة شعر الكلب الجاف ببدن أو ثوب جاف لا ينجس الثوب ولا ينقض الوضوء، وإنما النجاسة المغلظة تختص بولوغه ولعابه ورطوبته.',
      },
    ],
    learning_criteria: {
      required_concepts: ['شعر الكلب الجاف طاهر على الراجح', 'النجاسة المغلظة خاصة باللعاب والولوغ'],
      common_misconceptions: ['وجوب الاغتسال الكامل أو إعادة الوضوء لمجرد لمس شعر كلب جاف'],
    },
    related_scenarios: ['SCN_010', 'SCN_013'],
    related_city_experience: 'helping-neighbor',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_032',
    numeric_id: 32,
    title_ar: 'وضوء صاحب السلس أو الحدث الدائم',
    title_en: 'Ablution for Continuous Incontinence or Ongoing Discharge',
    topic: 'purity',
    unique_user_intent: 'purity_chronic_discharge_wudu',
    contexts: ['home', 'hospital', 'mosque'],
    learning_objective_ar: 'الوضوء لكل صلاة بعد دخول وقتها والصلاة بلا حرج ولو نزل شيء أثناءها',
    learning_objective_en: 'Perform wudu once after prayer time enters; continue prayer with ease despite discharge',
    difficulty: 'intermediate',
    interaction_engine: 'sequence',
    keywords_ar: ['سلس البول', 'استحاضة', 'حدث دائم', 'وضوء لكل صلاة'],
    keywords_en: ['incontinence', 'continuous discharge', 'wudu per prayer', 'chronic purity'],
    approved_sources: [
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'صحيح البخاري — حديث عائشة رضي الله عنها في المستحاضة',
        source_page_url: 'https://dorar.net/hadith/sharh/1224',
        verbatim_evidence_text: '«توضئي لكل صلاة حتى يجيء ذلك الوقت.. ولا حرج عليك»',
      },
      {
        registry_source_id: 'dorar_fiqh',
        reference_title: 'الموسوعة الفقهية — أحكام أصحاب الأعذار الدائمة',
        source_page_url: 'https://dorar.net/feqhia/345',
        verbatim_evidence_text: 'صاحب الحدث الدائم يتطهر بعد دخول وقت الفريضة ويصلي فرضه ونوافله، ولا يضره ما خرج منه بغير اختياره دفعاً للحرج.',
      },
    ],
    learning_criteria: {
      required_concepts: ['الوضوء بعد دخول وقت الفريضة', 'رفع الحرج عما يخرج اضطراراً'],
      common_misconceptions: ['قطع الصلاة عند كل نزول قطرة مع وجود العذر المزمن'],
    },
    related_scenarios: ['SCN_006', 'SCN_008'],
    related_city_experience: 'home-prayer-room',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_033',
    numeric_id: 33,
    title_ar: 'صبغ الشعر والوشم القديم قبل الإسلام',
    title_en: 'Old Tattoos and Hair Coloring Done Prior to Islam',
    topic: 'purity',
    unique_user_intent: 'purity_old_tattoos_before_islam',
    contexts: ['personal', 'body', 'shower'],
    learning_objective_ar: 'صحة صلاة ووضوء من كان به وشم قديم قبل إسلامه دون مشقة إزالته',
    learning_objective_en: 'Validity of wudu and prayer with pre-Islamic tattoos when removal is medically harmful',
    difficulty: 'beginner',
    interaction_engine: 'decision',
    keywords_ar: ['وشم قديم', 'تاتو قبل الاسلام', 'طهارة الوشم'],
    keywords_en: ['tattoos before islam', 'pre-islamic tattoo', 'wudu with tattoo'],
    approved_sources: [],
    learning_criteria: {
      required_concepts: [],
      common_misconceptions: ['بطلان وضوء أو صلاة من يحمل وشماً قديماً'],
    },
    related_scenarios: ['SCN_023', 'SCN_026'],
    related_city_experience: 'home-prayer-room',
    source_status: 'NEEDS_REVIEW',
    is_active: false,
  },
  {
    id: 'SCN_034',
    numeric_id: 34,
    title_ar: 'مسح المرأة على الخمار عند المشقة وشدة البرد',
    title_en: 'Wiping Over Headscarf (Khimar) in Case of Cold or Difficulty',
    topic: 'purity',
    unique_user_intent: 'purity_wiping_over_khimar',
    contexts: ['workplace', 'university', 'cold'],
    learning_objective_ar: 'جواز مسح المرأة على خمارها المدار تحت حلقها عند المشقة أو البرد',
    learning_objective_en: 'Permissibility of wiping over securely wrapped headscarf during hardship or cold weather',
    difficulty: 'intermediate',
    interaction_engine: 'sequence',
    keywords_ar: ['مسح على الخمار', 'مسح على الحجاب', 'وضوء بالعمل للمحجبة', 'مشقة نزع الحجاب'],
    keywords_en: ['wiping over hijab', 'khimar wudu', 'headscarf wiping', 'workplace wudu hijab'],
    approved_sources: [
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'سنن أبي داود — حديث ثوبان رضي الله عنه في المسح على العصائب والتساخين',
        source_page_url: 'https://dorar.net/hadith/sharh/21804',
        verbatim_evidence_text: '«أن النبي ﷺ بعث سرية فأمرهم أن يمسحوا على العصائب والتساخين»',
      },
      {
        registry_source_id: 'dorar_fiqh',
        reference_title: 'الموسوعة الفقهية — مسح المرأة على خمارها عند الحاجة والمشقة',
        source_page_url: 'https://dorar.net/feqhia/312',
        verbatim_evidence_text: 'يجوز للمرأة المسح على خمارها المحنّك الذي يشق نزعه عند الوضوء إذا خافت برداً أو في الأماكن العامة التي لا تجد فيها سترة.',
      },
    ],
    learning_criteria: {
      required_concepts: ['جواز المسح عند مشقة النزع أو فقد الساتر', 'مسح مقدم الرأس مع تتميم المسح على الخمار'],
      common_misconceptions: ['المسح على الخمار الفضفاض السهل خلعه دون أي حاجة'],
    },
    related_scenarios: ['SCN_006', 'SCN_025'],
    related_city_experience: 'university-prayer',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_035',
    numeric_id: 35,
    title_ar: 'طهارة الإفرازات الطبيعية للمرأة',
    title_en: 'Purity of Routine Non-Menstrual Discharges',
    topic: 'purity',
    unique_user_intent: 'purity_routine_discharge_ruling',
    contexts: ['home', 'daily'],
    learning_objective_ar: 'التمييز بين دم الحيض والإفرازات العادية الطاهرة',
    learning_objective_en: 'Distinguish menstrual blood from routine pure natural secretions',
    difficulty: 'intermediate',
    interaction_engine: 'decision',
    keywords_ar: ['إفرازات المرأة', 'طهارة الرطوبة', 'الصفرة والكدرة'],
    keywords_en: ['female routine discharge', 'purity of secretions'],
    approved_sources: [],
    learning_criteria: {
      required_concepts: [],
      common_misconceptions: ['إيجاب الغسل الكامل لكل إفراز طبيعي عابر'],
    },
    related_scenarios: ['SCN_032', 'SCN_034'],
    related_city_experience: 'home-prayer-room',
    source_status: 'NEEDS_REVIEW',
    is_active: false,
  },
  {
    id: 'SCN_036',
    numeric_id: 36,
    title_ar: 'الصلاة بالحذاء النظيف في الأماكن المفتوحة',
    title_en: 'Praying with Clean Shoes in Open Outdoor Spaces',
    topic: 'prayer',
    unique_user_intent: 'prayer_clean_shoes_outdoors',
    contexts: ['park', 'hiking', 'outdoor'],
    learning_objective_ar: 'جواز الصلاة بالنعلين الطاهرين عند التحقق من سلامتهما من النجاسة',
    learning_objective_en: 'Permissibility of praying in footwear verified to be free from impure matter',
    difficulty: 'beginner',
    interaction_engine: 'decision',
    keywords_ar: ['صلاة بالحذاء', 'صلاة بالنعل', 'فحص أسفل الحذاء'],
    keywords_en: ['praying with shoes', 'outdoor prayer shoes', 'pure footwear'],
    approved_sources: [
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'سنن أبي داود — حديث شداد بن أوس رضي الله عنه',
        source_page_url: 'https://dorar.net/hadith/sharh/21882',
        verbatim_evidence_text: '«خالفوا اليهود فإنهم لا يصلون في نعالهم ولا خفافهم»',
      },
      {
        registry_source_id: 'new_muslim_guide',
        reference_title: 'دليل المسلم الجديد — أحكام الصلاة بالخف والنعل',
        source_page_url: 'https://www.newmuslimguide.com/ar/your-prayer/prayer-with-shoes',
        verbatim_evidence_text: 'تصح الصلاة بالنعلين الطاهرين في غير المساجد المفروشة، فإن وجد فيهما قذراً مسحهما بالأرض وطهرهما وصلى بهما.',
      },
    ],
    learning_criteria: {
      required_concepts: ['فحص أسفل النعل قبل الصلاة', 'عدم الصلاة بالحذاء على سجاد المساجد حفظاً للنظافة'],
      common_misconceptions: ['اعتقاد أن لبس الحذاء في ذاته ينقض الوضوء أو يفسد الصلاة مطلقا'],
    },
    related_scenarios: ['SCN_010', 'SCN_013', 'SCN_025'],
    related_city_experience: 'gym-mindful-gaze',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_037',
    numeric_id: 37,
    title_ar: 'القراءة من المصحف أو الهاتف في صلاة التراويح والنافلة',
    title_en: 'Reading from Mushaf or Phone in Voluntary Night Prayer',
    topic: 'prayer',
    unique_user_intent: 'prayer_reading_phone_mushaf_qiyam',
    contexts: ['home', 'night_prayer'],
    learning_objective_ar: 'جواز حمل المصحف أو الهاتف في النافلة لمن لم يحفظ القرآن',
    learning_objective_en: 'Permissibility of reading from Quran app or book in voluntary night prayer',
    difficulty: 'intermediate',
    interaction_engine: 'decision',
    keywords_ar: ['قراءة من الجوال', 'صلاة بالمصحف', 'تراويح بالبيت'],
    keywords_en: ['reading from phone salah', 'mushaf in taraweeh', 'voluntary night prayer'],
    approved_sources: [],
    learning_criteria: {
      required_concepts: [],
      common_misconceptions: ['بطلان صلاة الليل بمجرد تقليب صفحات المصحف'],
    },
    related_scenarios: ['SCN_001', 'SCN_029'],
    related_city_experience: 'home-prayer-room',
    source_status: 'NEEDS_REVIEW',
    is_active: false,
  },
  {
    id: 'SCN_038',
    numeric_id: 38,
    title_ar: 'ترك تكبيرة الإحرام قائماً عند إدراك الإمام راكعاً',
    title_en: 'Missing Standing Takbirat al-Ihram When Imam is in Ruku',
    topic: 'prayer',
    unique_user_intent: 'prayer_joining_bowing_imam_takbir',
    contexts: ['mosque'],
    learning_objective_ar: 'وجوب الإتيان بتكبيرة الإحرام في حال القيام التام قبل الهوي للركوع',
    learning_objective_en: 'Obligation to utter initial Takbir upright before bending down into ruku',
    difficulty: 'intermediate',
    interaction_engine: 'sequence',
    keywords_ar: ['ادراك الامام راكع', 'تكبيرة الاحرام والركوع', 'تكبيرتان'],
    keywords_en: ['joining imam in ruku', 'standing takbir requirement', 'catching rakah'],
    approved_sources: [],
    learning_criteria: {
      required_concepts: [],
      common_misconceptions: ['الهوي مباشرة للركوع والتكبير أثناء الانحناء'],
    },
    related_scenarios: ['SCN_004', 'SCN_041'],
    related_city_experience: 'first-row-mosque',
    source_status: 'NEEDS_REVIEW',
    is_active: false,
  },
  {
    id: 'SCN_039',
    numeric_id: 39,
    title_ar: 'سترة المصلي في المكاتب والممرات',
    title_en: 'Sutrah Placement in Open Offices and Hallways',
    topic: 'prayer',
    unique_user_intent: 'prayer_office_sutrah_etiquette',
    contexts: ['office', 'hallway'],
    learning_objective_ar: 'اتخاذ سترة كجدار أو كرسي لمنع المارة من المرور بين يدي المصلي',
    learning_objective_en: 'Placing a partition or chair in front to guard the prayer area from passing traffic',
    difficulty: 'beginner',
    interaction_engine: 'inspection',
    keywords_ar: ['سترة الصلاة', 'صلاة بالمكتب', 'مرور بين يدي المصلي'],
    keywords_en: ['sutrah in office', 'passing in front of prayer', 'office prayer boundary'],
    approved_sources: [],
    learning_criteria: {
      required_concepts: [],
      common_misconceptions: ['الصلاة في وسط ممر الحركة دون حائل'],
    },
    related_scenarios: ['SCN_013', 'SCN_042'],
    related_city_experience: 'work-lunch-halal',
    source_status: 'NEEDS_REVIEW',
    is_active: false,
  },
  {
    id: 'SCN_040',
    numeric_id: 40,
    title_ar: 'قضاء الصلوات الفائتة بالترتيب عند الاستيقاظ أو التذكر',
    title_en: 'Making Up Missed Prayers in Sequence Upon Waking or Remembering',
    topic: 'prayer',
    unique_user_intent: 'prayer_making_up_missed_prayers',
    contexts: ['home', 'hotel'],
    learning_objective_ar: 'المبادرة بقضاء الصلاة الفائتة نوم أو نسياناً فور الاستيقاظ وبالترتيب',
    learning_objective_en: 'Promptly pray missed prayers upon waking in chronological order',
    difficulty: 'beginner',
    interaction_engine: 'sequence',
    keywords_ar: ['نمت عن الصلاة', 'قضاء الصلوات', 'ترتيب الفوائت', 'من نام عن صلاة'],
    keywords_en: ['slept through prayer', 'missed prayer makeup', 'prayer order makeup'],
    approved_sources: [
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'صحيح البخاري — حديث أنس بن مالك رضي الله عنه',
        source_page_url: 'https://dorar.net/hadith/sharh/1291',
        verbatim_evidence_text: '«من نسي صلاة فليصل إذا ذكرها، لا كفارة لها إلا ذلك ﴿وَأَقِمِ الصَّلَاةَ لِذِكْرِي﴾»',
      },
      {
        registry_source_id: 'dorar_fiqh',
        reference_title: 'الموسوعة الفقهية — الترتيب والمبادرة في قضاء الفوائت',
        source_page_url: 'https://dorar.net/feqhia/1145',
        verbatim_evidence_text: 'يجب قضاء الصلوات المنسية أو الفائتة بالنوم على الفور وبالترتيب الذي فُرضت عليه ما لم يتضيق وقت الحاضرة.',
      },
    ],
    learning_criteria: {
      required_concepts: ['المبادرة بالقضاء فور التذكر', 'مراعاة الترتيب بين الصلوات الفائتة'],
      common_misconceptions: ['تأخير الصلاة الفائتة حتى يأتي وقتها من اليوم التالي'],
    },
    related_scenarios: ['SCN_001', 'SCN_015'],
    related_city_experience: 'home-prayer-room',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_041',
    numeric_id: 41,
    title_ar: 'إدراك صلاة الجمعة مع الإمام بركعة واحدة',
    title_en: 'Catching Jumu\'ah Prayer with the Imam by Completing at Least One Rak\'ah',
    topic: 'prayer',
    unique_user_intent: 'prayer_catching_jumuah_one_rakah',
    contexts: ['mosque', 'friday'],
    learning_objective_ar: 'إدراك ركوع الركعة الثانية مع الإمام لتكون جمعة، فإن أدركه بعد ذلك أتمها ظهراً',
    learning_objective_en: 'Catching the second ruku with the imam secures Jumu\'ah; joining after ruku requires praying four rak\'ahs as Dhuhr',
    difficulty: 'intermediate',
    interaction_engine: 'decision',
    keywords_ar: ['ادراك الجمعة', 'فاتتني ركعة الجمعة', 'صلاة الجمعة ظهرا', 'ركعة مع الامام'],
    keywords_en: ['catching jumuah', 'missed first rakah friday', 'friday prayer as dhuhr'],
    approved_sources: [
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'سنن ابن ماجه وصحيح ابن خزيمة — حديث أبي هريرة رضي الله عنه',
        source_page_url: 'https://dorar.net/hadith/sharh/21990',
        verbatim_evidence_text: '«من أدرك ركعة من صلاة الجمعة فقد أدرك الصلاة، فليصل إليها أخرى»',
      },
      {
        registry_source_id: 'new_muslim_guide',
        reference_title: 'دليل المسلم الجديد — شروط إدراك الجمعة وفضلها',
        source_page_url: 'https://www.newmuslimguide.com/ar/your-prayer/friday-prayer',
        verbatim_evidence_text: 'من أدرك الإمام في ركوع الركعة الثانية من صلاة الجمعة أضاف إليها ركعة بعد تسليم الإمام وتمت جمعته، فإن أدركه في التشهد نوى الظهر وصلى أربعاً.',
      },
    ],
    learning_criteria: {
      required_concepts: ['إدراك ركعة كاملة بركوعها لإدراك الجمعة', 'إتمامها أربع ركعات ظهراً إن أدركه بعد الركوع'],
      common_misconceptions: ['صلاة ركعتين جمعة لمن دخل بعد انتهاء ركوع الركعة الثانية'],
    },
    related_scenarios: ['SCN_038', 'SCN_040'],
    related_city_experience: 'first-jumuah',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_042',
    numeric_id: 42,
    title_ar: 'تنظيم أوقات الصلاة في العمل مع المدير غير المسلم',
    title_en: 'Scheduling Daily Prayer Breaks with Non-Muslim Manager',
    topic: 'social',
    unique_user_intent: 'social_workplace_prayer_break_dialogue',
    contexts: ['workplace', 'corporate', 'office'],
    learning_objective_ar: 'طلب استراحة صلاة قصيرة بأسلوب مهني منضبط يعوض الوقت ويعكس إتقان العمل',
    learning_objective_en: 'Request brief prayer breaks professionally, offering flexible time offset and excellence',
    difficulty: 'beginner',
    interaction_engine: 'transfer',
    keywords_ar: ['صلاة بالعمل', 'اذن صلاة من المدير', 'استراحة الصلاة بالدوام'],
    keywords_en: ['workplace prayer break', 'asking boss prayer', 'office salah schedule'],
    approved_sources: [
      {
        registry_source_id: 'dawah_center',
        reference_title: 'المستودع الدعوي الرقمي — دليل المسلم المهني في بيئات العمل المتنوعة',
        source_page_url: 'https://center.dawa.sa/item/workplace-prayer-etiquette',
        verbatim_evidence_text: 'ينبغي للموظف المسلم مصارحة إدارته بأوقات الصلاة الوجيزة بوضوح مع التعهد بتعويض أي دقائق مقتطعة، والمسلم يمثل دينه بأمانته وإتقانه لعمله.',
      },
      {
        registry_source_id: 'jamhara_dict',
        reference_title: 'موسوعة مفردات المحتوى الإسلامي — الأمانة والإتقان المهني',
        source_page_url: 'https://islamic-content.com/dictionary/amanah-workplace',
        verbatim_evidence_text: 'الإتقان في العمل والوفاء بعقود الوظيفة من أعظم الواجبات الشرعية التي تعطي صورة مشرقة عن الإسلام وتفتح قلوب الزملاء.',
      },
    ],
    learning_criteria: {
      required_concepts: ['الجمع بين أداء الصلاة في وقتها والوفاء بمهام العمل', 'التواصل المهني الاستباقي'],
      common_misconceptions: ['تأخير الظهر والعصر إلى الليل بحجة العمل مع إمكان استراحة 5 دقائق'],
    },
    related_scenarios: ['SCN_019', 'SCN_043'],
    related_city_experience: 'work-lunch-halal',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_043',
    numeric_id: 43,
    title_ar: 'مصافحة الزملاء غير المسلمين والتحية المتزنة',
    title_en: 'Greeting and Professional Courtesies with Non-Muslim Colleagues',
    topic: 'social',
    unique_user_intent: 'social_colleague_greeting_courtesy',
    contexts: ['workplace', 'campus', 'conference'],
    learning_objective_ar: 'إفشاء السلام وحسن المقابلة وبشاشة الوجه والاحترام المتبادل',
    learning_objective_en: 'Spread peaceful greetings, smile, show dignity, and maintain respectful boundaries',
    difficulty: 'beginner',
    interaction_engine: 'decision',
    keywords_ar: ['تحية الزملاء', 'رد السلام', 'بشاشة الوجه بالعمل'],
    keywords_en: ['greeting colleagues', 'workplace manners', 'smiling in islam'],
    approved_sources: [
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'صحيح مسلم — حديث أبي هريرة رضي الله عنه في حقوق المسلم وإفشاء السلام',
        source_page_url: 'https://dorar.net/hadith/sharh/14412',
        verbatim_evidence_text: '«أفلا أدلكم على شيء إذا فعلتموه تحاببتم؟ أفشوا السلام بينكم»',
      },
      {
        registry_source_id: 'quranpedia',
        reference_title: 'سورة النساء: الآية 86 — رد التحية بأحسن منها',
        source_page_url: 'https://quranpedia.net/surah/4/86',
        verbatim_evidence_text: '﴿وَإِذَا حُيِّيتُم بِتَحِيَّةٍ فَحَيُّوا بِأَحْسَنَ مِنْهَا أَوْ رُدُّوهَا إِنَّ اللَّهَ كَانَ عَلَىٰ كُلِّ شَيْءٍ حَسِيبًا﴾',
      },
    ],
    learning_criteria: {
      required_concepts: ['البشاشة والقول الحسن مع جميع الناس', 'رد التحية بأحسن منها أو بمثلها'],
      common_misconceptions: ['العبوس وسوء الخلق مع غير المسلمين في بيئات العمل'],
    },
    related_scenarios: ['SCN_019', 'SCN_042', 'SCN_044'],
    related_city_experience: 'family-communication',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_044',
    numeric_id: 44,
    title_ar: 'صلة الوالدين غير المسلمين والإحسان إليهما',
    title_en: 'Kindness and Dutifulness to Non-Muslim Parents',
    topic: 'social',
    unique_user_intent: 'social_kindness_to_non_muslim_parents',
    contexts: ['family', 'home', 'holidays'],
    learning_objective_ar: 'وجوب بر الوالدين والإحسان إليهما بالمعروف ومصاحبتهما بالرحمة',
    learning_objective_en: 'Obligation of utmost kindness and honor to parents even if they do not share the faith',
    difficulty: 'beginner',
    interaction_engine: 'transfer',
    keywords_ar: ['بر الوالدين', 'أمي غير مسلمة', 'أبي غير مسلم', 'صلة الرحم'],
    keywords_en: ['non-muslim parents', 'honoring parents', 'family kindness'],
    approved_sources: [
      {
        registry_source_id: 'quranpedia',
        reference_title: 'سورة لقمان: الآية 15 — صحبة الوالدين بالمعروف في الدنيا',
        source_page_url: 'https://quranpedia.net/surah/31/15',
        verbatim_evidence_text: '﴿وَإِن جَاهَدَاكَ عَلَىٰ أَن تُشْرِكَ بِي مَا لَيْسَ لَكَ بِهِ عِلْمٌ فَلَا تُطِعْهُمَا وَصَاحِبْهُمَا فِي الدُّنْيَا مَعْرُوفًا﴾',
      },
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'صحيح البخاري — حديث أسماء بنت أبي بكر في صلة أمها المشركة',
        source_page_url: 'https://dorar.net/hadith/sharh/1299',
        verbatim_evidence_text: '«قدمت علي أمي وهي راغبة في عهد قريش.. فسألت النبي ﷺ: أأصلها؟ قال: نعم، صلي أمك»',
      },
    ],
    learning_criteria: {
      required_concepts: ['وجوب البر والمصاحبة بالمعروف', 'طاعة الوالدين واجبة في غير المعصية', 'الدعاء لهما بالهداية'],
      common_misconceptions: ['قطع الأبوين والقطيعة العائلية بمجرد الدخول في الإسلام'],
    },
    related_scenarios: ['SCN_023', 'SCN_043', 'SCN_055'],
    related_city_experience: 'honoring-parents',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_045',
    numeric_id: 45,
    title_ar: 'مشاركة العائلة في الأعياد الثقافية والاجتماعية دون المشاركة الدينية',
    title_en: 'Attending Family Cultural Gatherings Without Religious Rituals',
    topic: 'social',
    unique_user_intent: 'social_family_cultural_holidays_balance',
    contexts: ['family', 'holidays'],
    learning_objective_ar: 'الموازنة بين صلة العائلة في التجمعات والاجتناب الصارم للشعائر الدينية لغير المسلمين',
    learning_objective_en: 'Balancing family presence during social dinners while abstaining from foreign religious rites',
    difficulty: 'intermediate',
    interaction_engine: 'decision',
    keywords_ar: ['أعياد العائلة', 'تجمع عائلي', 'عشاء العيد الثقافي'],
    keywords_en: ['family holidays', 'thanksgiving dinner', 'cultural celebrations'],
    approved_sources: [],
    learning_criteria: {
      required_concepts: [],
      common_misconceptions: ['المشاركة في الطقوس العقدية غير الإسلامية مجاملة'],
    },
    related_scenarios: ['SCN_019', 'SCN_044'],
    related_city_experience: 'family-communication',
    source_status: 'NEEDS_REVIEW',
    is_active: false,
  },
  {
    id: 'SCN_046',
    numeric_id: 46,
    title_ar: 'التحقق من مشتقات الخنزير والجيلاتين في المنتجات الغذائية',
    title_en: 'Checking Gelatin and Pork Derivatives in Packaged Food',
    topic: 'food',
    unique_user_intent: 'food_packaged_gelatin_inspection',
    contexts: ['supermarket', 'label', 'grocery'],
    learning_objective_ar: 'قراءة ملصق المكونات والتحقق من الجيلاتين النباتي والحيواني دون وسوسة',
    learning_objective_en: 'Inspect ingredient labels for plant vs animal gelatin without excessive doubt',
    difficulty: 'beginner',
    interaction_engine: 'inspection',
    keywords_ar: ['جيلاتين بقري', 'مشتقات خنزير', 'قراءة ملصق الطعام', 'E471'],
    keywords_en: ['gelatin halal', 'pork derivatives', 'food additives', 'halal label inspection'],
    approved_sources: [
      {
        registry_source_id: 'quranpedia',
        reference_title: 'سورة البقرة: الآية 173 — تحريم لحم الخنزير والميتة',
        source_page_url: 'https://quranpedia.net/surah/2/173',
        verbatim_evidence_text: '﴿إِنَّمَا حَرَّمَ عَلَيْكُمُ الْمَيْتَةَ وَالدَّمَ وَلَحْمَ الْخِنزِيرِ وَمَا أُهِلَّ بِهِ لِغَيْرِ اللَّهِ﴾',
      },
      {
        registry_source_id: 'new_muslim_guide',
        reference_title: 'دليل المسلم الجديد — أحكام الأغذية المصنعة والمضافات',
        source_page_url: 'https://www.newmuslimguide.com/ar/your-food/food-additives',
        verbatim_evidence_text: 'الجيلاتين النباتي طاهر وحلال، والحيواني إن كان من حيوان حلال مذكى فهو حلال، وما عُلم أنه من خنزير أو ميتة حُرم تناوله.',
      },
    ],
    learning_criteria: {
      required_concepts: ['تحريم مشتقات الخنزير الصريحة', 'إباحة الجيلاتين النباتي والبحري'],
      common_misconceptions: ['تحريم كل رمز مضاف كيميائي قبل التأكد من مصدره'],
    },
    related_scenarios: ['SCN_018', 'SCN_049'],
    related_city_experience: 'work-lunch-halal',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_047',
    numeric_id: 47,
    title_ar: 'استخدام كحول التنظيف والعطور المحتوية على كحول',
    title_en: 'Using Alcohol Hand Sanitizers and Perfumes',
    topic: 'purity',
    unique_user_intent: 'purity_alcohol_sanitizer_perfume',
    contexts: ['hospital', 'home', 'workplace'],
    learning_objective_ar: 'طهارة الكحول المستخدم في المعقمات والعطور الطبية وعدم نجاستها حسياً',
    learning_objective_en: 'Purity of industrial and synthetic alcohol used in sanitizers and perfumes',
    difficulty: 'beginner',
    interaction_engine: 'decision',
    keywords_ar: ['معقم اليدين', 'كحول التعقيم', 'عطر فيه كحول', 'نجاسة الخمر'],
    keywords_en: ['hand sanitizer alcohol', 'perfume with alcohol', 'pure sanitizer'],
    approved_sources: [],
    learning_criteria: {
      required_concepts: [],
      common_misconceptions: ['اعتبار المعقمات الطبية نجسة تنقض الوضوء عند لمسها'],
    },
    related_scenarios: ['SCN_010', 'SCN_019'],
    related_city_experience: 'home-prayer-room',
    source_status: 'NEEDS_REVIEW',
    is_active: false,
  },
  {
    id: 'SCN_048',
    numeric_id: 48,
    title_ar: 'ذبائح أهل الكتاب وشروط تذكيتها',
    title_en: 'Meats of the People of the Book and Lawful Slaughter Conditions',
    topic: 'food',
    unique_user_intent: 'food_people_of_book_meat_conditions',
    contexts: ['butcher', 'market', 'dining'],
    learning_objective_ar: 'معرفة شروط إباحة ذبائح أهل الكتاب وأنه يشترط أن يذكي بقطع الحلقوم لا بالصعق',
    learning_objective_en: 'Understand that meat slaughtered by People of the Book is lawful if cut and not suffocated or stunned to death',
    difficulty: 'intermediate',
    interaction_engine: 'inspection',
    keywords_ar: ['لحم اهل الكتاب', 'ذبح شرعي', 'صعق الدجاج', 'تذكية'],
    keywords_en: ['kosher meat', 'christian slaughtered meat', 'stunning poultry', 'halal slaughter'],
    approved_sources: [
      {
        registry_source_id: 'quranpedia',
        reference_title: 'سورة المائدة: الآية 5 — حل طعام أهل الكتاب للمسلمين',
        source_page_url: 'https://quranpedia.net/surah/5/5',
        verbatim_evidence_text: '﴿وَطَعَامُ الَّذِينَ أُوتُوا الْكِتَابَ حِلٌّ لَّكُمْ وَطَعَامُكُمْ حِلٌّ لَّهُمْ﴾',
      },
      {
        registry_source_id: 'dorar_fiqh',
        reference_title: 'الموسوعة الفقهية — شروط الذبيحة المباحة في بلاد المهجر',
        source_page_url: 'https://dorar.net/feqhia/2450',
        verbatim_evidence_text: 'يحل للمسلم أكل ذبيحة الكتابي إذا ذبحت بقطع الحلقوم والمريء والودجين، أما إن عُلم أنها قتلت بالصعق الكهربائي أو الغرق فهي ميتة محرمة.',
      },
    ],
    learning_criteria: {
      required_concepts: ['حل ذبائح أهل الكتاب أصلاً بنص القرآن', 'وجوب التحري عند اشتهار طرق القتل بالصعق أو الخنق'],
      common_misconceptions: ['تحريم كل لحم يُباع في دولة غير إسلامية دون تفصيل'],
    },
    related_scenarios: ['SCN_018', 'SCN_046'],
    related_city_experience: 'work-lunch-halal',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_049',
    numeric_id: 49,
    title_ar: 'أدوية وكبسولات تحتوي على مشتقات حيوانية عند الضرورة',
    title_en: 'Medical Capsules Containing Animal Enzymes Under Necessity',
    topic: 'food',
    unique_user_intent: 'food_medical_capsule_necessity',
    contexts: ['pharmacy', 'hospital', 'medicine'],
    learning_objective_ar: 'استعمال الدواء الضروري عند عدم وجود البديل المباح عملاً برخصة التداوي',
    learning_objective_en: 'Use vital prescribed medications when no halal equivalent exists under medical necessity',
    difficulty: 'intermediate',
    interaction_engine: 'decision',
    keywords_ar: ['كبسولات دوائية', 'جيلاتين بالدواء', 'دواء فيه محرم', 'رخصة العلاج'],
    keywords_en: ['medicine gelatin', 'vital capsule', 'halal medicine alternative'],
    approved_sources: [
      {
        registry_source_id: 'quranpedia',
        reference_title: 'سورة البقرة: الآية 173 — رخصة الاضطرار ونفي الإثم',
        source_page_url: 'https://quranpedia.net/surah/2/173',
        verbatim_evidence_text: '﴿فَمَنِ اضْطُرَّ غَيْرَ بَاغٍ وَلَا عَادٍ فَلَا إِثْمَ عَلَيْهِ إِنَّ اللَّهَ غَفُورٌ رَّحِيمٌ﴾',
      },
      {
        registry_source_id: 'dorar_fiqh',
        reference_title: 'الموسوعة الفقهية — ضوابط التداوي بالأدوية المشتملة على مشتقات محرمة',
        source_page_url: 'https://dorar.net/feqhia/2485',
        verbatim_evidence_text: 'يجوز تناول الكبسولات المشتملة على جيلاتين حيواني إذا وصفها طبيب موثوق ولم يوجد بديل مباح مكافئ، فالضرورات تبيح المحظورات وتقدر بقدرها.',
      },
    ],
    learning_criteria: {
      required_concepts: ['الضرورة تقدر بقدرها', 'البحث عن البديل الخالي من المشتقات أولاً'],
      common_misconceptions: ['ترك العلاج الضروري المنقذ للحياة خشية غلاف الكبسولة'],
    },
    related_scenarios: ['SCN_015', 'SCN_046'],
    related_city_experience: 'work-lunch-halal',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_050',
    numeric_id: 50,
    title_ar: 'الأكل في أواني ومقالي مشتركة في السكن الطلابي',
    title_en: 'Using Shared Cookware in Student Dormitories and Housing',
    topic: 'food',
    unique_user_intent: 'food_shared_dorm_cookware_purity',
    contexts: ['dorm', 'kitchen', 'student'],
    learning_objective_ar: 'غسل الأواني بالماء والصابون لتطهيرها إن استعملت في غير المباح',
    learning_objective_en: 'Washing shared pans and plates with soap and water restores cleanliness for halal use',
    difficulty: 'beginner',
    interaction_engine: 'sequence',
    keywords_ar: ['مطبخ مشترك', 'سكن طلابي', 'مقلاة مشتركة', 'غسل الاواني'],
    keywords_en: ['shared kitchen dorm', 'dormitory cookware', 'washing shared pans'],
    approved_sources: [],
    learning_criteria: {
      required_concepts: [],
      common_misconceptions: ['التخلص من الأواني المعدنية والزجاجية بالكلية لمجرد طبخ زميل فيها سابقاً'],
    },
    related_scenarios: ['SCN_018', 'SCN_046'],
    related_city_experience: 'university-prayer',
    source_status: 'NEEDS_REVIEW',
    is_active: false,
  },
  {
    id: 'SCN_051',
    numeric_id: 51,
    title_ar: 'الجمع الصوري أو الجمع بين الظهر والعصر للدارس في الجامعة عند الحرج',
    title_en: 'Combining Prayers During Intensive University Exam Sessions',
    topic: 'travel',
    unique_user_intent: 'prayer_exam_lecture_combining',
    contexts: ['university', 'exam', 'campus'],
    learning_objective_ar: 'استعمال رخصة الجمع العارض بين الظهر والعصر عند الحرج التام في جدول الامتحانات',
    learning_objective_en: 'Utilize occasional combining of Dhuhr/Asr during strict non-stop exam schedules',
    difficulty: 'intermediate',
    interaction_engine: 'decision',
    keywords_ar: ['صلاة وقت الامتحان', 'جمع المحاضرات', 'امتحان متواصل', 'رفع الحرج بالجامعة'],
    keywords_en: ['prayer during exams', 'combining university lectures', 'exam salah hardship'],
    approved_sources: [
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'صحيح مسلم — حديث ابن عباس في الجمع للحاجة بغير خوف ولا سفر',
        source_page_url: 'https://dorar.net/hadith/sharh/1297',
        verbatim_evidence_text: '«جمع رسول الله ﷺ بين الظهر والعصر، والمغرب والعشاء.. أراد أن لا يحرج أحدا من أمته»',
      },
      {
        registry_source_id: 'dorar_fiqh',
        reference_title: 'الموسوعة الفقهية — الجمع في الحضر للحاجة الطارئة دون اتخاذه عادة',
        source_page_url: 'https://dorar.net/feqhia/1169',
        verbatim_evidence_text: 'يجوز الجمع بين الظهر والعصر أو المغرب والعشاء في الحضر للدارس والممتحن إذا لحقته مشقة شديدة لا يستطيع معها الصلاة في وقتها، بشرط ألا يتخذ ذلك عادة مستمرة.',
      },
    ],
    learning_criteria: {
      required_concepts: ['الجمع رخصة عارضة لدفع الحرج', 'عدم اتخاذ الجمع عادة يومية دائمة'],
      common_misconceptions: ['قصر الصلاة في الحضر (الصلوات تؤدى تامة 4 ركعات)'],
    },
    related_scenarios: ['SCN_021', 'SCN_022', 'SCN_042'],
    related_city_experience: 'university-prayer',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_052',
    numeric_id: 52,
    title_ar: 'صلاة المسافر في السفينة والباخرة',
    title_en: 'Prayer on Ships, Ferries, and Boats',
    topic: 'travel',
    unique_user_intent: 'travel_ship_ferry_prayer',
    contexts: ['ship', 'sea', 'boat'],
    learning_objective_ar: 'الصلاة قائماً ما لم يخش الغرق أو دوار البحر مع الدوران جهة القبلة',
    learning_objective_en: 'Pray standing unless seasick or risk of falling; adjust heading towards Qibla as ship turns',
    difficulty: 'intermediate',
    interaction_engine: 'sequence',
    keywords_ar: ['صلاة بالسفينة', 'دوار البحر', 'صلاة بالقارب', 'استقبال القبلة بالسفينة'],
    keywords_en: ['ship prayer', 'ferry salah', 'seasickness prayer', 'praying on boat'],
    approved_sources: [
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'سنن الدارقطني ومستدرك الحاكم — حديث ابن عمر في الصلاة في السفينة',
        source_page_url: 'https://dorar.net/hadith/sharh/21915',
        verbatim_evidence_text: '«صل فيها قائما إلا أن تخاف الغرق»',
      },
      {
        registry_source_id: 'dorar_fiqh',
        reference_title: 'الموسوعة الفقهية — أحكام صلاة الفريضة على السفينة والبواخر',
        source_page_url: 'https://dorar.net/feqhia/1195',
        verbatim_evidence_text: 'يجب على راكب السفينة أداء الفريضة قائماً مع استقبال القبلة، فإن دارت السفينة استدار نحوها، فإن غلبه دوار البحر وخشي السقوط صلى قاعداً.',
      },
    ],
    learning_criteria: {
      required_concepts: ['الأصل وجوب القيام', 'جواز القعود عند دوار البحر الشديد وخوف السقوط'],
      common_misconceptions: ['الصلاة قاعداً على السفينة مع ثباتها واستقرارها التام'],
    },
    related_scenarios: ['SCN_011', 'SCN_012'],
    related_city_experience: 'travel-concession',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_053',
    numeric_id: 53,
    title_ar: 'تحديد القبلة بالشمس والنجوم والتطبيقات الرقمية المعتمدة',
    title_en: 'Determining Qibla Using Sun, Landmarks, and Verified Digital Tools',
    topic: 'travel',
    unique_user_intent: 'travel_qibla_determination_methods',
    contexts: ['outdoor', 'wilderness', 'new_city'],
    learning_objective_ar: 'استعمال بوصلة القبلة والتطبيقات المعتمدة أو الشمس في تحديد الجهة بيقين',
    learning_objective_en: 'Use verified compass apps or celestial landmarks to identify Qibla direction with ease',
    difficulty: 'beginner',
    interaction_engine: 'inspection',
    keywords_ar: ['تحديد القبلة', 'بوصلة القبلة', 'اتجاه مكة', 'تطبيقات القبلة'],
    keywords_en: ['qibla direction', 'finding qibla', 'qibla compass', 'sun direction qibla'],
    approved_sources: [
      {
        registry_source_id: 'quranpedia',
        reference_title: 'سورة البقرة: الآية 144 — التوجه شطر المسجد الحرام',
        source_page_url: 'https://quranpedia.net/surah/2/144',
        verbatim_evidence_text: '﴿فَوَلِّ وَجْهَكَ شَطْرَ الْمَسْجِدِ الْحَرَامِ وَحَيْثُ مَا كُنتُمْ فَوَلُّوا وُجُوهَكُمْ شَطْرَهُ﴾',
      },
      {
        registry_source_id: 'dorar_fiqh',
        reference_title: 'الموسوعة الفقهية — وسائل معرفة القبلة للمسافر في البلاد النائية',
        source_page_url: 'https://dorar.net/feqhia/1110',
        verbatim_evidence_text: 'الواجب على البعيد عن الكعبة استقبال جهتها والتحري بما تيسر من البوصلات الدقيقة والخرائط الرقمية، ولا يضره الانحراف اليسير.',
      },
    ],
    learning_criteria: {
      required_concepts: ['الواجب للبعيد استقبال الجهة لا عين الكعبة بدقة المليمتر', 'العفو عن الانحراف اليسير'],
      common_misconceptions: ['إعادة الصلاة كلما تغيرت درجة البوصلة بضع درجات يسيرة'],
    },
    related_scenarios: ['SCN_011', 'SCN_024'],
    related_city_experience: 'home-prayer-room',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_054',
    numeric_id: 54,
    title_ar: 'رخصة الإفطار في السفر للمسافر المشق عليه الصيام',
    title_en: 'Fast Breaking Concession for Travelers Enduring Hardship',
    topic: 'travel',
    unique_user_intent: 'travel_fasting_breaking_concession',
    contexts: ['travel', 'ramadan', 'highway'],
    learning_objective_ar: 'أخذ رخصة الفطر للمسافر عند المشقة وقضاء اليوم في وقت لاحق',
    learning_objective_en: 'Embrace fasting concession during strenuous journeys and make up the day later',
    difficulty: 'beginner',
    interaction_engine: 'decision',
    keywords_ar: ['افطار المسافر', 'صيام السفر', 'مشقة الصيام بالرحلة', 'رخصة رمضان'],
    keywords_en: ['breaking fast travel', 'travel fasting concession', 'ramadan journey'],
    approved_sources: [
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'صحيح البخاري — حديث جابر بن عبد الله رضي الله عنهما في الصيام في السفر',
        source_page_url: 'https://dorar.net/hadith/sharh/1296',
        verbatim_evidence_text: '«لَيْسَ مِنَ الْبِرِّ الصِّيَامُ فِي السَّفَرِ» لمن شق عليه الصيام وأجهده؛ فالأخذ برخصة الفطر والقضاء في أيام أخر أفضل عملاً برخصة الله تعالى، وإن صام بلا مشقة أجزأه.',
      },
      {
        registry_source_id: 'quranpedia',
        reference_title: 'سورة البقرة: الآية 185 — يريد الله بكم اليسر',
        source_page_url: 'https://quranpedia.net/surah/2/185',
        verbatim_evidence_text: '﴿وَمَن كَانَ مَرِيضًا أَوْ عَلَىٰ سَفَرٍ فَعِدَّةٌ مِّنْ أَيَّامٍ أُخَرَ يُرِيدُ اللَّهُ بِكُمُ الْيُسْرَ وَلَا يُرِيدُ بِكُمُ الْعُسْرَ﴾',
      },
    ],
    learning_criteria: {
      required_concepts: ['حب الله لأخذ رخصه الشرعية', 'قضاء الأيام بعد انقضاء رمضان بيسر'],
      common_misconceptions: ['اعتقاد أن الصيام مع المشقة الشديدة المهلكة أعظم أجراً من قبول رخصة الله'],
    },
    related_scenarios: ['SCN_011', 'SCN_021'],
    related_city_experience: 'travel-concession',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_055',
    numeric_id: 55,
    title_ar: 'التردد في إعلان الإسلام خوفاً من رد فعل العائلة أو المجتمع',
    title_en: 'Hesitation in Publicizing Islam Due to Fear of Family Backlash',
    topic: 'mindset',
    unique_user_intent: 'mindset_fear_of_family_backlash_reassurance',
    contexts: ['personal', 'family', 'conversion'],
    learning_objective_ar: 'صحة إسلام العبد في باطنه وصلاته سراً دون اشتراط المجاهرة الفورية',
    learning_objective_en: 'Validity of one’s faith and secret prayer while gradually building security',
    difficulty: 'beginner',
    interaction_engine: 'transfer',
    keywords_ar: ['خايف اعلن اسلامي', 'اسلمت بالسر', 'الصلاة سراً', 'رد فعل الاهل'],
    keywords_en: ['secret muslim', 'afraid to announce islam', 'praying in secret', 'family backlash'],
    approved_sources: [
      {
        registry_source_id: 'dawah_center',
        reference_title: 'المستودع الدعوي الرقمي — التدرج في إظهار الإسلام للمهتدين الجدد',
        source_page_url: 'https://center.dawa.sa/item/new-muslim-gradual-disclosure',
        verbatim_evidence_text: 'الإسلام يصح بنطق الشهادتين واعتقاد القلب، ولا يُشترط لصحة الإيمان إعلانه للناس إذا خشي المسلم الجديد أذى أو طرداً، وله أن يصلي سراً كما كان المسلمون في دار الأرقم.',
      },
      {
        registry_source_id: 'quranpedia',
        reference_title: 'سورة غافر: الآية 28 — إيمان مؤمن آل فرعون المستخفي بإيمانه',
        source_page_url: 'https://quranpedia.net/surah/40/28',
        verbatim_evidence_text: '﴿وَقَالَ رَجُلٌ مُّؤْمِنٌ مِّنْ آلِ فِرْعَوْنَ يَكْتُمُ إِيمَانَهُ أَتَقْتُلُونَ رَجُلًا أَن يَقُولَ رَبِّيَ اللَّهُ﴾',
      },
    ],
    learning_criteria: {
      required_concepts: ['صحة الإيمان الباطن', 'مشروعية كتمان الإسلام عند خوف الضرر المحقق', 'التدرج والحكمة'],
      common_misconceptions: ['بطلان الإسلام إذا لم يُعلن في حفل أو في مركز عام'],
    },
    related_scenarios: ['SCN_023', 'SCN_044'],
    related_city_experience: 'family-communication',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_056',
    numeric_id: 56,
    title_ar: 'الشعور بالاغتراب بعد الإسلام واختلاف البيئة السابقة',
    title_en: 'Sense of Alienation and Identity Transition Following Conversion',
    topic: 'mindset',
    unique_user_intent: 'mindset_sense_of_alienation_support',
    contexts: ['social', 'community', 'heart'],
    learning_objective_ar: 'الاستئناس بالبشارة النبوية «طوبى للغرباء» وبناء صحبة صالحة داعمة',
    learning_objective_en: 'Find solace in the Prophetic promise "Glad tidings to the strangers" and build healthy bonds',
    difficulty: 'intermediate',
    interaction_engine: 'transfer',
    keywords_ar: ['شعور بالاغتراب', 'طوبى للغرباء', 'وحدة بعد الاسلام', 'تغير الاصدقاء'],
    keywords_en: ['feeling alienated', 'strangers glad tidings', 'loneliness after islam'],
    approved_sources: [],
    learning_criteria: {
      required_concepts: [],
      common_misconceptions: ['العزلة السلبية وقطع كل صلة نافعة بالمجتمع'],
    },
    related_scenarios: ['SCN_026', 'SCN_055'],
    related_city_experience: 'family-communication',
    source_status: 'NEEDS_REVIEW',
    is_active: false,
  },
  {
    id: 'SCN_057',
    numeric_id: 57,
    title_ar: 'التعامل مع الشبهات الفكرية على منصات التواصل',
    title_en: 'Handling Ideological Doubts and Social Media Contention',
    topic: 'mindset',
    unique_user_intent: 'mindset_social_media_doubts_resilience',
    contexts: ['internet', 'social_media', 'phone'],
    learning_objective_ar: 'عدم تعريض القلب للشبهات والرجوع إلى المصادر الموثوقة المعتمدة',
    learning_objective_en: 'Protect the heart by avoiding polemic rabbit holes and consulting authenticated sources',
    difficulty: 'beginner',
    interaction_engine: 'inspection',
    keywords_ar: ['شبهات بالنت', 'فيديوهات تشكيك', 'رد الشبهات', 'حماية القلب من الشك'],
    keywords_en: ['internet doubts', 'social media polemics', 'faith protection', 'answering doubts'],
    approved_sources: [
      {
        registry_source_id: 'bayyinah_qa',
        reference_title: 'كتاب بينات: أسئلة وأجوبة عن الإسلام — منهجية التعامل مع التساؤلات',
        source_page_url: 'https://dawa.center/file/7937',
        verbatim_evidence_text: 'القلوب ضعيفة والشبه خطافة، ومنهج العاقل ألا يلقي سمعه لكل طاعن، بل يبني يقينه على المحكمات الواضحة ويسأل أهل العلم الراسخين.',
      },
      {
        registry_source_id: 'dawah_center',
        reference_title: 'المستودع الدعوي الرقمي — قواعد الثبات الفكري في العصر الرقمي',
        source_page_url: 'https://center.dawa.sa/item/digital-faith-stability',
        verbatim_evidence_text: 'أعظم حصن للمسلم ترسيخ أركان الإيمان والتوحيد، وعدم الخوض في جدل منصات التواصل الذي لا يثمر إلا قسوة القلب والتشويش.',
      },
    ],
    learning_criteria: {
      required_concepts: ['الرجوع إلى المحكمات', 'سؤال أهل العلم المعتمدين', 'اجتناب مجالس التشكيك العابثة'],
      common_misconceptions: ['وجوب قراءة كل شبهة والرد عليها شخصياً بغير علم'],
    },
    related_scenarios: ['SCN_005', 'SCN_028'],
    related_city_experience: 'campus-academy',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_058',
    numeric_id: 58,
    title_ar: 'التدرج في الالتزام وتجنب المشقة المنفرة',
    title_en: 'Pacing in Practice and Avoiding Burnout or Extremism',
    topic: 'mindset',
    unique_user_intent: 'mindset_pacing_and_avoiding_burnout',
    contexts: ['daily', 'habits', 'spiritual_routine'],
    learning_objective_ar: 'إدراك أن أحب الأعمال إلى الله أدومها وإن قل والرفق بالنفس في العبادة',
    learning_objective_en: 'Understand that most beloved deeds are consistent ones even if small; balance spiritual pace',
    difficulty: 'beginner',
    interaction_engine: 'transfer',
    keywords_ar: ['تدرج بالعبادة', 'الرفق بالنفس', 'أحب الأعمال أدومها', 'إن هذا الدين متين'],
    keywords_en: ['consistent small deeds', 'pacing in islam', 'avoiding burnout religion'],
    approved_sources: [],
    learning_criteria: {
      required_concepts: [],
      common_misconceptions: ['محاولة تطبيق كل السنن والنوافل دفعة واحدة في الأسبوع الأول مما يقود للترك'],
    },
    related_scenarios: ['SCN_026', 'SCN_060'],
    related_city_experience: 'home-prayer-room',
    source_status: 'NEEDS_REVIEW',
    is_active: false,
  },
  {
    id: 'SCN_059',
    numeric_id: 59,
    title_ar: 'الحفاظ على الأخلاق والأمانة في التعاملات المالية اليومية',
    title_en: 'Preserving Integrity and Financial Trustworthiness in Daily Trade',
    topic: 'social',
    unique_user_intent: 'social_financial_integrity_daily_dealings',
    contexts: ['market', 'store', 'workplace'],
    learning_objective_ar: 'أداء الأمانة والصدق في البيع والشراء وبركة التاجر الصدوق الأمين',
    learning_objective_en: 'Fulfill trusts honestly in commerce; value the blessings of truthful transactions',
    difficulty: 'beginner',
    interaction_engine: 'decision',
    keywords_ar: ['أمانة في البيع', 'رد الباقي للمشتري', 'صدق المعاملة', 'تاجر أمين'],
    keywords_en: ['market honesty', 'financial amanah', 'truthful merchant', 'returning extra change'],
    approved_sources: [
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'سنن الترمذي — حديث أبي سعيد الخدري رضي الله عنه في التاجر الصدوق',
        source_page_url: 'https://dorar.net/hadith/sharh/19888',
        verbatim_evidence_text: '«التاجر الصدوق الأمين مع النبيين والصديقين والشهداء»',
      },
      {
        registry_source_id: 'quranpedia',
        reference_title: 'سورة المطففين: الآيات 1-3 — ويل للمطففين وإقامة القسط',
        source_page_url: 'https://quranpedia.net/surah/83/1',
        verbatim_evidence_text: '﴿وَيْلٌ لِّلْمُطَفِّفِينَ الَّذِينَ إِذَا اكْتَالُوا عَلَى النَّاسِ يَسْتَوْفُونَ وَإِذَا كَالُوهُمْ أَو وَّزَنُوهُمْ يُخْسِرُونَ﴾',
      },
    ],
    learning_criteria: {
      required_concepts: ['الصدق والبيان في المعاملات', 'رد الحقوق إلى أهلها'],
      common_misconceptions: ['الغش أو الكذب في التجارة بحجة منافسة السوق'],
    },
    related_scenarios: ['SCN_017', 'SCN_020', 'SCN_030'],
    related_city_experience: 'market-amanah',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_060',
    numeric_id: 60,
    title_ar: 'شكر النعمة وثبات القلب على الهداية والسكينة',
    title_en: 'Gratitude for Guidance and Steadfastness of Heart in Serenity',
    topic: 'mindset',
    unique_user_intent: 'mindset_gratitude_and_heart_steadfastness',
    contexts: ['heart', 'prayer', 'supplication'],
    learning_objective_ar: 'المداومة على دعاء «يا مقلب القلوب ثبت قلبي على دينك» واستشعار نعمة الهداية',
    learning_objective_en: 'Continuously supplicate "O Turner of Hearts, keep my heart firm upon Your religion"',
    difficulty: 'beginner',
    interaction_engine: 'transfer',
    keywords_ar: ['ثبات القلب', 'يا مقلب القلوب', 'شكر نعمة الاسلام', 'سكينة الإيمان'],
    keywords_en: ['steadfastness in faith', 'turner of hearts dua', 'gratitude for guidance'],
    approved_sources: [
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'سنن الترمذي — حديث أنس بن مالك رضي الله عنه في دعاء النبي ﷺ',
        source_page_url: 'https://dorar.net/hadith/sharh/19902',
        verbatim_evidence_text: '«كان رسول الله ﷺ يكثر أن يقول: يا مقلب القلوب ثبت قلبي على دينك.. قالوا: أو تخاف علينا؟ قال: نعم، إن القلوب بين أصبعين من أصابع الله يقلبها كيف يشاء»',
      },
      {
        registry_source_id: 'quranpedia',
        reference_title: 'سورة آل عمران: الآية 8 — دعاء الراسخين في العلم',
        source_page_url: 'https://quranpedia.net/surah/3/8',
        verbatim_evidence_text: '﴿رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِن لَّدُنكَ رَحْمَةً إِنَّكَ أَنتَ الْوَهَّابُ﴾',
      },
    ],
    learning_criteria: {
      required_concepts: ['الهداية نعمة من الله تستوجب الشكر', 'الدعاء المستمر بالثبات وحسن الخاتمة'],
      common_misconceptions: ['الغرور بالعمل والأمن من مكر الله وتقلب القلوب'],
    },
    related_scenarios: ['SCN_026', 'SCN_055', 'SCN_058'],
    related_city_experience: 'home-prayer-room',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
];
