import { ScenarioKnowledgeItem } from '../types/scenarioKnowledge';

export const SCENARIO_DATA_PART_1: ScenarioKnowledgeItem[] = [
  {
    id: 'SCN_001',
    numeric_id: 1,
    title_ar: 'نسيان التشهد الأول والقيام للثالثة',
    title_en: 'Missed First Tashahhud and Stood Up',
    topic: 'prayer',
    unique_user_intent: 'prayer_missed_first_tashahhud',
    contexts: ['home', 'mosque', 'prayer_room'],
    learning_objective_ar: 'الاستمرار في القيام وعدم الرجوع للجلوس وسجود السهو قبل السلام',
    learning_objective_en: 'Continue standing without returning to sit, perform Sujud Sahw before tasleem',
    difficulty: 'beginner',
    interaction_engine: 'sequence',
    keywords_ar: ['تشهد اول', 'نسيت التشهد', 'قمت للثالثة', 'سجود السهو'],
    keywords_en: ['missed tashahhud', 'first tashahhud', 'stood up', 'forgetfulness prostration'],
    approved_sources: [
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'صحيح البخاري — حديث عبد الله بن بحينة رضي الله عنه',
        source_page_url: 'https://dorar.net/hadith/sharh/1294',
        verbatim_evidence_text: '«إذا قام أحدكم في الركعتين فلم يستتم قائما فليجلس، فإذا استتم قائما فلا يجلس ويسجد سجدتي السهو»',
      },
      {
        registry_source_id: 'new_muslim_guide',
        reference_title: 'دليل المسلم الجديد — أحكام سجود السهو ومجبرات الصلاة',
        source_page_url: 'https://www.newmuslimguide.com/ar/your-prayer/sujud-as-sahw',
        verbatim_evidence_text: 'إذا نسي المصلي التشهد الأول واستتم قائماً كره له الرجوع ويجبره بسجدتين للسهو قبل السلام.',
      },
    ],
    learning_criteria: {
      required_concepts: ['الاستمرار في الركعة الثالثة', 'سجدتا السهو قبل السلام'],
      common_misconceptions: ['قطع الصلاة وإعادتها من الأول', 'الرجوع للجلوس بعد استتمام القيام'],
    },
    related_scenarios: ['SCN_002', 'SCN_004', 'SCN_005'],
    related_city_experience: 'home-prayer-room',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_002',
    numeric_id: 2,
    title_ar: 'الشك في عدد الركعات (3 أم 4)',
    title_en: 'Doubt in Rak\'ah Count (3 or 4)',
    topic: 'prayer',
    unique_user_intent: 'prayer_doubt_in_rakah_count',
    contexts: ['home', 'mosque', 'workplace'],
    learning_objective_ar: 'طرح الشك والبناء على اليقين وهو الأقل وسجود السهو',
    learning_objective_en: 'Discard doubt, build upon certainty (the lesser count), and prostrate for forgetfulness',
    difficulty: 'beginner',
    interaction_engine: 'decision',
    keywords_ar: ['شك بالركعات', 'صليت ثلاث او اربع', 'البناء على اليقين'],
    keywords_en: ['doubt rakah', 'three or four', 'build on certainty'],
    approved_sources: [
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'صحيح مسلم — حديث أبي سعيد الخدري رضي الله عنه',
        source_page_url: 'https://dorar.net/hadith/sharh/14352',
        verbatim_evidence_text: '«إذا شك أحدكم في صلاته فلم يدر كم صلى، ثلاثا أم أربعا، فليطرح الشك وليبن على ما استيقن ثم يسجد سجدتين قبل أن يسلم»',
      },
      {
        registry_source_id: 'dorar_fiqh',
        reference_title: 'الموسوعة الفقهية — قاعدة البناء على الأقل عند الشك',
        source_page_url: 'https://dorar.net/feqhia/1460',
        verbatim_evidence_text: 'إذا تردد المصلي بين الأقل والأكثر بنى على الأقل لأنه المتيقن، وأتى بما بقي وسجد للسهو.',
      },
    ],
    learning_criteria: {
      required_concepts: ['البناء على اليقين', 'طرح الشك المتأخر'],
      common_misconceptions: ['إلغاء الصلاة كاملة والبدء من جديد', 'الاعتماد على الظن المجرد دون يقين'],
    },
    related_scenarios: ['SCN_001', 'SCN_005'],
    related_city_experience: 'home-prayer-room',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_003',
    numeric_id: 3,
    title_ar: 'الضحك أو الكلام سهواً في الصلاة',
    title_en: 'Unintentional Speech or Laughter in Prayer',
    topic: 'prayer',
    unique_user_intent: 'prayer_unintentional_laughter_speech',
    contexts: ['mosque', 'home'],
    learning_objective_ar: 'معرفة الفرق بين التبسم والقهقهة وحكم الكلام الساهي',
    learning_objective_en: 'Distinguish smiling from audible laughter and accidental speech ruling',
    difficulty: 'intermediate',
    interaction_engine: 'decision',
    keywords_ar: ['ضحكت بالصلاة', 'كلام ساهي', 'تبسم'],
    keywords_en: ['laughter in prayer', 'spoke accidentally', 'smile vs laughter'],
    approved_sources: [],
    learning_criteria: {
      required_concepts: [],
      common_misconceptions: ['التبسم يبطل الصلاة كالضحك'],
    },
    related_scenarios: ['SCN_001', 'SCN_004'],
    related_city_experience: 'home-prayer-room',
    source_status: 'NEEDS_REVIEW',
    is_active: false,
  },
  {
    id: 'SCN_004',
    numeric_id: 4,
    title_ar: 'نسيان سجدة أو ركوع والانتباه في الركعة التالية',
    title_en: 'Missed Pillar (Sujud or Ruku) Realized in Next Rak\'ah',
    topic: 'prayer',
    unique_user_intent: 'prayer_missed_essential_pillar',
    contexts: ['home', 'mosque'],
    learning_objective_ar: 'إلغاء الركعة الناقصة ركناً وإقامة التالية مقامها وسجود السهو',
    learning_objective_en: 'Nullify the incomplete rakah, replace it with the next, and perform Sujud Sahw',
    difficulty: 'intermediate',
    interaction_engine: 'sequence',
    keywords_ar: ['نسيت سجدة', 'نسيت ركوع', 'نسيان ركن', 'إلغاء الركعة'],
    keywords_en: ['missed sujud', 'missed ruku', 'missed pillar', 'rakah replacement'],
    approved_sources: [
      {
        registry_source_id: 'dorar_fiqh',
        reference_title: 'الموسوعة الفقهية — تدارك الأركان المنسية في الصلاة',
        source_page_url: 'https://dorar.net/feqhia/1468',
        verbatim_evidence_text: 'إلغاء الركعة التي نسي ركنها إذا شرع في قراءة الركعة التالية، وإقامة الركعة التالية مقامها، وسجود السهو بعد السلام؛ أو الإتيان بالركن وتداركه إن لم يشرع في قراءة التالية.',
      },
      {
        registry_source_id: 'new_muslim_guide',
        reference_title: 'دليل المسلم الجديد — الفرق بين الواجب والركن عند النسيان',
        source_page_url: 'https://www.newmuslimguide.com/ar/your-prayer/pillars-of-prayer',
        verbatim_evidence_text: 'الركن لا يسقط سهواً ولا عمداً ولا بد من الإتيان به، فإن تذكره قبل الشروع في التالية أتى به وما بعده، وإن شرع في التالية لغت الركعة الناقصة وقامت هذه مقامها.',
      },
    ],
    learning_criteria: {
      required_concepts: ['الركن لا يسقط بالسهو', 'إلغاء الركعة الناقصة عند الشروع في التالية'],
      common_misconceptions: ['جبر الركن المتروك بسجود السهو فقط دون قضاء الركعة'],
    },
    related_scenarios: ['SCN_001', 'SCN_002'],
    related_city_experience: 'home-prayer-room',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_005',
    numeric_id: 5,
    title_ar: 'وسواس الصلاة وشرود الذهن المتكرر (وسوسة خنزب)',
    title_en: 'Waswas and Intrusive Thoughts in Prayer',
    topic: 'mindset',
    unique_user_intent: 'prayer_intrusive_thoughts_waswas',
    contexts: ['home', 'mosque', 'university'],
    learning_objective_ar: 'الاستعاذة بالله من خنزب والنفث عن اليسار ثلاثاً واستحضار السكينة',
    learning_objective_en: 'Seek refuge from Khanzab, lightly spit three times to the left, and restore tranquility',
    difficulty: 'beginner',
    interaction_engine: 'transfer',
    keywords_ar: ['وسواس', 'خنزب', 'تشتت الذهن', 'النفث عن اليسار'],
    keywords_en: ['waswas', 'intrusive thoughts', 'khanzab', 'loss of focus'],
    approved_sources: [
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'صحيح مسلم — حديث عثمان بن أبي العاص في شيطان الصلاة خنزب',
        source_page_url: 'https://dorar.net/hadith/sharh/26227',
        verbatim_evidence_text: '«ذاك شيطان يقال له خنزب، فإذا أحسسته فتعوذ بالله منه واتفل على يسارك ثلاثا، قال: ففعلت ذلك فأذهبه الله عني»',
      },
      {
        registry_source_id: 'dawah_center',
        reference_title: 'المستودع الدعوي الرقمي — علاج الوسواس وتثبيت الطمأنينة للمهتدين',
        source_page_url: 'https://center.dawa.sa/item/waswas-remedy',
        verbatim_evidence_text: 'الوسوسة في الصلاة دليل على حرص الشيطان على إفساد الخشوع، وعلاجها الاستعاذة بالله والإعراض عن الشكوك وعدم قطع الفريضة.',
      },
    ],
    learning_criteria: {
      required_concepts: ['الاستعاذة النبوية من خنزب', 'النهي عن قطع الصلاة بسبب الوسواس'],
      common_misconceptions: ['قطع الصلاة وإعادتها كلما طرأت وسوسة', 'الشعور بالذنب المبالغ فيه من طروء الأفكار العابرة'],
    },
    related_scenarios: ['SCN_002', 'SCN_026'],
    related_city_experience: 'home-prayer-room',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_006',
    numeric_id: 6,
    title_ar: 'المسح على الجبيرة أو الضمادة الطبية',
    title_en: 'Wiping Over Medical Cast or Wound Bandage',
    topic: 'purity',
    unique_user_intent: 'purity_wiping_over_medical_cast',
    contexts: ['home', 'hospital', 'clinic'],
    learning_objective_ar: 'المسح على الجبيرة بالماء مباشرة دون غسل الموضع المتضرر حتى يبرأ',
    learning_objective_en: 'Wipe directly with wet hands over the medical cast without washing the injured site',
    difficulty: 'beginner',
    interaction_engine: 'sequence',
    keywords_ar: ['جبيرة', 'ضمادة', 'مسح على الجبس', 'وضوء الجريح'],
    keywords_en: ['cast', 'bandage', 'medical wrap', 'wiping injured limb'],
    approved_sources: [
      {
        registry_source_id: 'dorar_fiqh',
        reference_title: 'الموسوعة الفقهية — أحكام المسح على الجبائر والضمادات',
        source_page_url: 'https://dorar.net/feqhia/320',
        verbatim_evidence_text: 'يمسح على الجبيرة بالماء مباشرة دون غسل الموضع المتضرر حتى يبرأ، ولا يشترط لبسها على طهارة على الراجح الميسر، ولا يُنتقل للتيمم إلا إذا تضرر الموضع بالمسح أيضاً.',
      },
      {
        registry_source_id: 'new_muslim_guide',
        reference_title: 'دليل المسلم الجديد — رخصة المسح على الجبيرة واللفافة',
        source_page_url: 'https://www.newmuslimguide.com/ar/your-purification/wiping-over-cast',
        verbatim_evidence_text: 'الجبيرة يمسح عليها كلها بالماء عند الوضوء والغسل حفظاً للعضو ورفعاً للحرج حتى يزول العذر.',
      },
    ],
    learning_criteria: {
      required_concepts: ['المسح باليد المبللة على ظاهر الجبيرة', 'استمرار الرخصة حتى الشفاء'],
      common_misconceptions: ['اشتراط لبس الجبيرة على طهارة سابقة كالخفين', 'إعادة الوضوء بالتيمم إذا كان المسح كافياً'],
    },
    related_scenarios: ['SCN_007', 'SCN_009', 'SCN_025'],
    related_city_experience: 'home-prayer-room',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_007',
    numeric_id: 7,
    title_ar: 'شدة البرد والعجز عن استعمال الماء البارد',
    title_en: 'Severe Cold and Inability to Use Unheated Water',
    topic: 'purity',
    unique_user_intent: 'purity_extreme_cold_concession',
    contexts: ['home', 'travel', 'outdoor'],
    learning_objective_ar: 'استعمال رخصة التيمم عند الخوف من المرض أو الضرر بالبرد',
    learning_objective_en: 'Use tayammum concession when fearing severe illness or harm from freezing water',
    difficulty: 'beginner',
    interaction_engine: 'decision',
    keywords_ar: ['برد قارس', 'ماء بارد', 'خوف المرض', 'تيمم للبرد'],
    keywords_en: ['severe cold', 'freezing water', 'cold tayammum', 'harm prevention'],
    approved_sources: [
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'سنن أبي داود وصحيح ابن حبان — حديث عمرو بن العاص في تيمم الجنابة للبرد',
        source_page_url: 'https://dorar.net/hadith/sharh/21894',
        verbatim_evidence_text: '«احتلمت في ليلة باردة في غزوة ذات السلاسل فأشفقت إن اغتسلت أن أهلك فتيممت ثم صليت.. فضحك رسول الله ﷺ ولم يقل شيئا»',
      },
      {
        registry_source_id: 'dorar_fiqh',
        reference_title: 'الموسوعة الفقهية — التيمم لعذر البرد الشديد مع تعذر التسخين',
        source_page_url: 'https://dorar.net/feqhia/362',
        verbatim_evidence_text: 'يجوز التيمم لمن خاف ضرراً محققاً أو زيادة مرض باستعمال الماء البارد الشديد إذا عجز عن تسخينه.',
      },
    ],
    learning_criteria: {
      required_concepts: ['حفظ النفس ودفع المشقة غير المحتملة', 'البحث عن التسخين أولاً فإن تعذر فالتيمم'],
      common_misconceptions: ['التيمم للبرد مع القدرة على تسخين الماء بيسر', 'ترك الصلاة حتى خروج وقتها'],
    },
    related_scenarios: ['SCN_006', 'SCN_009', 'SCN_022'],
    related_city_experience: 'home-prayer-room',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_008',
    numeric_id: 8,
    title_ar: 'الشك الطارئ في انتقاض الوضوء أثناء الصلاة',
    title_en: 'Sudden Doubt of Breaking Wudu While Praying',
    topic: 'purity',
    unique_user_intent: 'purity_phantom_doubt_in_prayer',
    contexts: ['mosque', 'home'],
    learning_objective_ar: 'اليقين لا يزول بالشك والنهي عن الانصراف إلا بسماع صوت أو وجدان ريح',
    learning_objective_en: 'Certainty is not removed by doubt; do not leave prayer without hearing sound or smelling odor',
    difficulty: 'beginner',
    interaction_engine: 'decision',
    keywords_ar: ['شك بالوضوء', 'انتقاض وضوء', 'ريح بالصلاة'],
    keywords_en: ['doubt wudu', 'breaking ablution', 'wind in prayer'],
    approved_sources: [],
    learning_criteria: {
      required_concepts: [],
      common_misconceptions: ['قطع الصلاة بمجرد حركة الأمعاء أو التردد الذهني'],
    },
    related_scenarios: ['SCN_002', 'SCN_005'],
    related_city_experience: 'home-prayer-room',
    source_status: 'NEEDS_REVIEW',
    is_active: false,
  },
  {
    id: 'SCN_009',
    numeric_id: 9,
    title_ar: 'التيمم عند فقد الماء أو المرض المانع',
    title_en: 'Tayammum When Water is Unavailable or Harmful',
    topic: 'purity',
    unique_user_intent: 'purity_dry_ablution_procedure',
    contexts: ['travel', 'hospital', 'home'],
    learning_objective_ar: 'تعلم صفة التيمم الصحيحة بضربة واحدة للوجه والكفين بالصعيد الطيب',
    learning_objective_en: 'Learn correct Tayammum: one strike on clean earth for face and hands',
    difficulty: 'beginner',
    interaction_engine: 'sequence',
    keywords_ar: ['تيمم', 'فقد الماء', 'صعيد طيب', 'ضربة واحدة'],
    keywords_en: ['tayammum', 'dry ablution', 'clean earth', 'no water'],
    approved_sources: [
      {
        registry_source_id: 'quranpedia',
        reference_title: 'سورة المائدة: الآية 6 — تشريع التيمم والتيسير',
        source_page_url: 'https://quranpedia.net/surah/5/6',
        verbatim_evidence_text: '﴿فَلَمْ تَجِدُوا مَاءً فَتَيَمَّمُوا صَعِيدًا طَيِّبًا فَامْسَحُوا بِوُجُوهِكُمْ وَأَيْدِيكُم مِّنْهُ مَا يُرِيدُ اللَّهُ لِيَجْعَلَ عَلَيْكُم مِّنْ حَرَجٍ﴾',
      },
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'صحيح البخاري — حديث عمار بن ياسر في صفة التيمم ضربة واحدة',
        source_page_url: 'https://dorar.net/hadith/sharh/1218',
        verbatim_evidence_text: '«إنما كان يكفيك أن تصنع هكذا: فضرب بكفيه ضربة على الأرض ثم نفضهما، ثم مسح بهما وجهه وكفيه»',
      },
    ],
    learning_criteria: {
      required_concepts: ['ضربة واحدة على صعيد طاهر', 'مسح الوجه وباطن وظاهر الكفين'],
      common_misconceptions: ['المسح إلى المرفقين أو ضربات متعددة', 'التيمم مع وجود الماء والقدرة على استعماله بلا ضرر'],
    },
    related_scenarios: ['SCN_006', 'SCN_007', 'SCN_011'],
    related_city_experience: 'home-prayer-room',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_010',
    numeric_id: 10,
    title_ar: 'طين الشوارع ورذاذ المطر المصيب للثياب',
    title_en: 'Street Mud and Rain Splashes on Garments',
    topic: 'purity',
    unique_user_intent: 'purity_street_mud_cleanliness',
    contexts: ['street', 'workplace', 'rain'],
    learning_objective_ar: 'إدراك أن الأصل في طين الشوارع الطهارة والمشقة تجلب التيسير',
    learning_objective_en: 'Recognize that street mud is pure by default and hardship brings ease',
    difficulty: 'beginner',
    interaction_engine: 'inspection',
    keywords_ar: ['طين الشارع', 'وحل المطر', 'الأصل الطهارة', 'رذاذ الطرقات'],
    keywords_en: ['street mud', 'rain splashes', 'purity default', 'wet pavements'],
    approved_sources: [
      {
        registry_source_id: 'dorar_fiqh',
        reference_title: 'الموسوعة الفقهية — قاعدة الطهارة في طين الشوارع',
        source_page_url: 'https://dorar.net/feqhia/285',
        verbatim_evidence_text: 'الأصل في طين الشوارع والمياه الجارية في الطرقات الطهارة ما لم تُتيقن النجاسة بعينها أو ريحها، والمشقة تجلب التيسير، وما أصاب الثوب أو البدن معفو عنه.',
      },
      {
        registry_source_id: 'dawah_center',
        reference_title: 'المستودع الدعوي الرقمي — رفع الوسوسة في طهارة الملابس والأرصفة',
        source_page_url: 'https://center.dawa.sa/item/street-purity',
        verbatim_evidence_text: 'الشريعة مبنية على التيسير ونفي الحرج، وما يصيب ثياب المارة في الطرقات من وحل أو طين معفو عنه شرعاً حتى يتيقن المسلم عين النجاسة.',
      },
    ],
    learning_criteria: {
      required_concepts: ['الأصل في الأشياء الطهارة', 'العفو عما يشق التحرز منه'],
      common_misconceptions: ['افتراض نجاسة كل ماء في الشارع وتغيير الثياب وجوباً'],
    },
    related_scenarios: ['SCN_006', 'SCN_022'],
    related_city_experience: 'street-honesty-amanah',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_011',
    numeric_id: 11,
    title_ar: 'صلاة الفريضة في الطائرة عند تعذر الوقوف',
    title_en: 'Obligatory Prayer in Airplane Seat When Standing is Impossible',
    topic: 'travel',
    unique_user_intent: 'travel_airplane_seat_prayer',
    contexts: ['airplane', 'flight'],
    learning_objective_ar: 'أداء الصلاة جالساً بالإيماء للركوع والسجود عند تعذر الوقوف وخشية خروج الوقت',
    learning_objective_en: 'Perform prayer seated with nodding gestures for ruku and sujud when standing is unsafe',
    difficulty: 'intermediate',
    interaction_engine: 'sequence',
    keywords_ar: ['صلاة بالطيارة', 'كرسي الطائرة', 'الإيماء بالركوع', 'خروج وقت الصلاة'],
    keywords_en: ['airplane prayer', 'seated prayer', 'flight salah', 'nodding gesture'],
    approved_sources: [
      {
        registry_source_id: 'dorar_fiqh',
        reference_title: 'الموسوعة الفقهية — كيفية صلاة الفريضة في وسائل النقل الجوي',
        source_page_url: 'https://dorar.net/feqhia/1188',
        verbatim_evidence_text: 'إذا خشي خروج الوقت ولم يتمكن من الصلاة قائماً ومستقبلاً للقبلة في الطائرة، صلى على حسب استطاعته جالساً ويومئ بالركوع والسجود وسجوده أخفض من ركوعه.',
      },
      {
        registry_source_id: 'new_muslim_guide',
        reference_title: 'دليل المسلم الجديد — أحكام الصلاة في السفر والمواصلات',
        source_page_url: 'https://www.newmuslimguide.com/ar/your-prayer/prayer-in-travel',
        verbatim_evidence_text: 'المسلم يصلي الفريضة في الطائرة إذا خشي فوات وقتها ولم يمكنه الجمع، فإن عجز عن القيام صلى قاعداً وأومأ بركوعه وسجوده.',
      },
    ],
    learning_criteria: {
      required_concepts: ['الصلاة بحسب الاستطاعة ﴿فَاتَّقُوا اللَّهَ مَا اسْتَطَعْتُمْ﴾', 'جعل إيماء السجود أخفض من الركوع'],
      common_misconceptions: ['تأخير الصلاة حتى يخرج وقتها بالكلية مع إمكان أدائها في الطائرة'],
    },
    related_scenarios: ['SCN_012', 'SCN_014', 'SCN_021'],
    related_city_experience: 'travel-concession',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_012',
    numeric_id: 12,
    title_ar: 'أداء الصلاة في القطار أو الحافلة العامة',
    title_en: 'Prayer in Moving Train or Public Bus',
    topic: 'travel',
    unique_user_intent: 'travel_train_bus_prayer',
    contexts: ['train', 'bus', 'public_transport'],
    learning_objective_ar: 'استقبال القبلة عند الإحرام والتحري حسب القدرة والإيماء عند العجز',
    learning_objective_en: 'Face Qibla at Takbirat al-Ihram if feasible, and pray with gestures if standing unsafe',
    difficulty: 'intermediate',
    interaction_engine: 'decision',
    keywords_ar: ['صلاة بالقطار', 'صلاة بالباص', 'استقبال القبلة بالمواصلات'],
    keywords_en: ['train prayer', 'bus salah', 'facing qibla transport'],
    approved_sources: [
      {
        registry_source_id: 'dorar_fiqh',
        reference_title: 'الموسوعة الفقهية — صلاة الفريضة في القطار والحافلة',
        source_page_url: 'https://dorar.net/feqhia/1192',
        verbatim_evidence_text: 'استقبال القبلة عند تكبيرة الإحرام والتحري حسب القدرة والمحافظة على أركان الصلاة من قيام وركوع وسجود ما أمكن، فإن تعذر صلى قاعداً وأومأ بالركوع والسجود جاعلاً سجوده أخفض من ركوعه لقوله تعالى ﴿فَاتَّقُوا اللَّهَ مَا اسْتَطَعْتُمْ﴾.',
      },
      {
        registry_source_id: 'quranpedia',
        reference_title: 'سورة التغابن: الآية 16 — مبدأ الاستطاعة الشرعية',
        source_page_url: 'https://quranpedia.net/surah/64/16',
        verbatim_evidence_text: '﴿فَاتَّقُوا اللَّهَ مَا اسْتَطَعْتُمْ وَاسْمَعُوا وَأَطِيعُوا وَأَنفِقُوا خَيْرًا لِّأَنفُسِكُمْ﴾',
      },
    ],
    learning_criteria: {
      required_concepts: ['التحري واستقبال القبلة ابتداءً ما أمكن', 'انتقال البدل عند العجز عن القيام'],
      common_misconceptions: ['الصلاة قاعداً مع القدرة التامة والآمنة على القيام والركوع'],
    },
    related_scenarios: ['SCN_011', 'SCN_014'],
    related_city_experience: 'travel-concession',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_013',
    numeric_id: 13,
    title_ar: 'الصلاة في الأماكن العامة والحدائق المفتوحة',
    title_en: 'Prayer in Public Spaces and Open Parks',
    topic: 'prayer',
    unique_user_intent: 'prayer_public_park_etiquette',
    contexts: ['park', 'public_square', 'nature'],
    learning_objective_ar: 'إدراك أن الأرض كلها مسجد وطهور واختيار مكان طاهر ساتر',
    learning_objective_en: 'Understand that all earth is made a clean place of prayer; choose clean location',
    difficulty: 'beginner',
    interaction_engine: 'inspection',
    keywords_ar: ['صلاة بالحديقة', 'الصلاة بالشارع', 'جعلت لي الارض مسجدا'],
    keywords_en: ['park prayer', 'open area salah', 'earth is a mosque'],
    approved_sources: [
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'صحيح البخاري — حديث جابر بن عبد الله رضي الله عنهما',
        source_page_url: 'https://dorar.net/hadith/sharh/1077',
        verbatim_evidence_text: '«وجعلت لي الأرض مسجدا وطهورا، فأيما رجل من أمتي أدركته الصلاة فليصل»',
      },
      {
        registry_source_id: 'dawah_center',
        reference_title: 'المستودع الدعوي الرقمي — سمت المسلم عند الصلاة في الفضاء المفتوح',
        source_page_url: 'https://center.dawa.sa/item/public-prayer-etiquette',
        verbatim_evidence_text: 'تصح الصلاة في أي بقعة طاهرة من الأرض كالمتنزهات والميادين، مع مراعاة ستر العورة وعدم تعطيل طرقات المشاة.',
      },
    ],
    learning_criteria: {
      required_concepts: ['طهارة الأرض أصلاً', 'مراعاة حقوق الطريق والمشاة'],
      common_misconceptions: ['اشتراط وجود سجادة صلاة مخصصة دائماً للصحة'],
    },
    related_scenarios: ['SCN_010', 'SCN_014', 'SCN_036'],
    related_city_experience: 'home-prayer-room',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_014',
    numeric_id: 14,
    title_ar: 'الصلاة في المطار أو محطات السفر',
    title_en: 'Prayer in Airport Terminals and Travel Stations',
    topic: 'travel',
    unique_user_intent: 'travel_airport_transit_prayer',
    contexts: ['airport', 'terminal', 'station'],
    learning_objective_ar: 'الاستفادة من مصليات المطارات أو الأركان الهادئة مع رخصة الجمع والقصر',
    learning_objective_en: 'Utilize airport prayer rooms or quiet corners with travel concessions',
    difficulty: 'beginner',
    interaction_engine: 'transfer',
    keywords_ar: ['صلاة بالمطار', 'ترانزيت', 'قصر الصلاة بالمطار'],
    keywords_en: ['airport prayer', 'transit salah', 'shortening in airport'],
    approved_sources: [
      {
        registry_source_id: 'dorar_fiqh',
        reference_title: 'الموسوعة الفقهية — صلاة المسافر في صالات المغادرة والمطارات',
        source_page_url: 'https://dorar.net/feqhia/1175',
        verbatim_evidence_text: 'المسافر إذا غادر عمران بلده ودخل صالة المطار المسافر منها جاز له الترخص برخص السفر من قصر وجمع عند الحاجة.',
      },
      {
        registry_source_id: 'new_muslim_guide',
        reference_title: 'دليل المسلم الجديد — رخص السفر في المطارات والمحطات',
        source_page_url: 'https://www.newmuslimguide.com/ar/your-prayer/travel-rulings',
        verbatim_evidence_text: 'يبدأ قصر الصلاة الرباعية ركعتين والجمع بعد مفارقة مباني المدينة والوصول إلى بوابة السفر الدولية.',
      },
    ],
    learning_criteria: {
      required_concepts: ['بداية الترخص بمفارقة العمران', 'الجمع بين الظهر والعصر أو المغرب والعشاء'],
      common_misconceptions: ['القصر في المنزل قبل التحرك للمطار'],
    },
    related_scenarios: ['SCN_011', 'SCN_021', 'SCN_025'],
    related_city_experience: 'travel-concession',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_015',
    numeric_id: 15,
    title_ar: 'الصلاة قبل أو بعد العمليات الجراحية للمريض',
    title_en: 'Prayer for Patients Around Surgical Procedures',
    topic: 'prayer',
    unique_user_intent: 'prayer_patient_surgical_concession',
    contexts: ['hospital', 'clinic'],
    learning_objective_ar: 'جمع الصلاتين تقديماً أو تأخيراً قبل التخدير والصلاة حسب الاستطاعة',
    learning_objective_en: 'Combine prayers before anesthesia and pray according to capability upon waking',
    difficulty: 'intermediate',
    interaction_engine: 'decision',
    keywords_ar: ['صلاة المريض', 'عملية جراحية', 'بنج', 'تخدير', 'جمع للمرض'],
    keywords_en: ['patient prayer', 'surgery salah', 'anesthesia prayer', 'combining for illness'],
    approved_sources: [
      {
        registry_source_id: 'dorar_fiqh',
        reference_title: 'الموسوعة الفقهية — جمع الصلاة للمريض والمقبل على عملية جراحية',
        source_page_url: 'https://dorar.net/feqhia/1160',
        verbatim_evidence_text: 'يجوز للمريض المقبل على عملية جراحية يستغرق وقتها وقتاً لصلاة أخرى أن يجمع جمع تقديم أو تأخير لرفع الحرج.',
      },
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'صحيح البخاري — حديث عمران بن حصين في صلاة المريض',
        source_page_url: 'https://dorar.net/hadith/sharh/1117',
        verbatim_evidence_text: '«صل قائما، فإن لم تستطع فقاعدا، فإن لم تستطع فعلى جنب»',
      },
    ],
    learning_criteria: {
      required_concepts: ['صلاة المريض على قدر الاستطاعة', 'مشروعية الجمع للحاجة الطبية'],
      common_misconceptions: ['ترك الصلاة بالكلية ظناً أن العملية تسقط الفريضة'],
    },
    related_scenarios: ['SCN_006', 'SCN_009', 'SCN_040'],
    related_city_experience: 'home-prayer-room',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_016',
    numeric_id: 16,
    title_ar: 'قبول هدية أو طعام من الجار غير المسلم',
    title_en: 'Accepting Gifts or Food from Non-Muslim Neighbor',
    topic: 'social',
    unique_user_intent: 'social_neighbor_gift_acceptance',
    contexts: ['neighborhood', 'home'],
    learning_objective_ar: 'جواز قبول الهدية وحسن المعاشرة وبر الجار ما لم يكن محرماً بعينه',
    learning_objective_en: 'Permissibility of accepting gifts and being kind to neighbors unless intrinsically forbidden',
    difficulty: 'beginner',
    interaction_engine: 'decision',
    keywords_ar: ['هدية الجار', 'جار غير مسلم', 'طعام الجار', 'البر بالقسط'],
    keywords_en: ['neighbor gift', 'non-muslim food', 'kindness to neighbor'],
    approved_sources: [],
    learning_criteria: {
      required_concepts: [],
      common_misconceptions: ['تحريم أي طعام أو هدية تأتي من غير المسلمين مطلقاً'],
    },
    related_scenarios: ['SCN_018', 'SCN_044'],
    related_city_experience: 'helping-neighbor',
    source_status: 'NEEDS_REVIEW',
    is_active: false,
  },
  {
    id: 'SCN_017',
    numeric_id: 17,
    title_ar: 'التعامل مع الفوائد البنكية الربوية الطارئة',
    title_en: 'Handling Incidental Bank Usury and Interest Accruals',
    topic: 'social',
    unique_user_intent: 'social_bank_interest_disposal',
    contexts: ['bank', 'financial'],
    learning_objective_ar: 'التخلص من الفائدة الربوية بصرفها في مصالح المسلمين العامة دون نية الصدقة',
    learning_objective_en: 'Dispose of interest gains into general public welfare without expecting charity reward',
    difficulty: 'intermediate',
    interaction_engine: 'transfer',
    keywords_ar: ['فوائد بنكية', 'ربا', 'تخلص من الفائدة', 'حساب بنكي'],
    keywords_en: ['bank interest', 'riba disposal', 'financial ethics'],
    approved_sources: [],
    learning_criteria: {
      required_concepts: [],
      common_misconceptions: ['إبقاء الفائدة في البنك للمؤسسة الربوية أو أكلها شخصياً'],
    },
    related_scenarios: ['SCN_020', 'SCN_059'],
    related_city_experience: 'street-honesty-amanah',
    source_status: 'NEEDS_REVIEW',
    is_active: false,
  },
  {
    id: 'SCN_018',
    numeric_id: 18,
    title_ar: 'تناول الأطعمة واللحوم في بلاد غير المسلمين وتدقيق الحلال',
    title_en: 'Food and Meat Inspection in Non-Muslim Countries',
    topic: 'food',
    unique_user_intent: 'food_halal_meat_inspection',
    contexts: ['restaurant', 'market', 'abroad'],
    learning_objective_ar: 'التحقق من حل الذبيحة وإباحة الأطعمة النباتية والأسماك دون وسوسة',
    learning_objective_en: 'Verify lawful slaughter, and utilize default permissibility for seafood and plants',
    difficulty: 'beginner',
    interaction_engine: 'inspection',
    keywords_ar: ['لحم حلال', 'طعام بالخارج', 'ذبيحة', 'سمك حلال', 'خنزير'],
    keywords_en: ['halal meat', 'kosher vs halal', 'food abroad', 'pork derivatives'],
    approved_sources: [
      {
        registry_source_id: 'quranpedia',
        reference_title: 'سورة المائدة: الآية 5 — طعام أهل الكتاب والطيبات',
        source_page_url: 'https://quranpedia.net/surah/5/5',
        verbatim_evidence_text: '﴿الْيَوْمَ أُحِلَّ لَكُمُ الطَّيِّبَاتُ وَطَعَامُ الَّذِينَ أُوتُوا الْكِتَابَ حِلٌّ لَّكُمْ وَطَعَامُكُمْ حِلٌّ لَّهُمْ﴾',
      },
      {
        registry_source_id: 'new_muslim_guide',
        reference_title: 'دليل المسلم الجديد — ضوابط الأطعمة والأشربة في بلاد الغرب',
        source_page_url: 'https://www.newmuslimguide.com/ar/your-food/halal-and-haram',
        verbatim_evidence_text: 'الأصل في جميع الأطعمة الحل إلا ما دل الدليل على تحريمه كالخنزير والميتة والمسكر، وذبائح أهل الكتاب حلال ما لم يُعلم ذبحها على غير وجه شرعي كالصعق.',
      },
    ],
    learning_criteria: {
      required_concepts: ['الأصل في الأطعمة الحل', 'حل ذبائح أهل الكتاب المستوفية للشروط', 'حل صيد البحر'],
      common_misconceptions: ['افتراض تحريم كل مطعم يقدم مأكولات بحرية أو نباتية'],
    },
    related_scenarios: ['SCN_019', 'SCN_046', 'SCN_048'],
    related_city_experience: 'work-lunch-halal',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_019',
    numeric_id: 19,
    title_ar: 'حضور دعوة عمل في مطعم يقدّم الخمور',
    title_en: 'Attending Business Meal in Venue Serving Alcohol',
    topic: 'food',
    unique_user_intent: 'food_business_lunch_alcohol_venue',
    contexts: ['workplace', 'restaurant', 'corporate'],
    learning_objective_ar: 'المحافظة على مائدة خالية من المنكر وطلب الجلوس في مكان مستقل بوقار',
    learning_objective_en: 'Ensure one’s immediate table is free from alcohol and request dignified seating',
    difficulty: 'intermediate',
    interaction_engine: 'decision',
    keywords_ar: ['عزومة عمل', 'مطعم فيه خمر', 'طاولة خالية من الخمر', 'عشاء مهني'],
    keywords_en: ['business lunch', 'alcohol served', 'work dinner', 'table etiquette'],
    approved_sources: [
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'سنن الترمذي — حديث جابر بن عبد الله رضي الله عنه في مجالس الخمر',
        source_page_url: 'https://dorar.net/hadith/sharh/19904',
        verbatim_evidence_text: '«من كان يؤمن بالله واليوم الآخر فلا يجلس على مائدة يدار عليها الخمر»',
      },
      {
        registry_source_id: 'dawah_center',
        reference_title: 'المستودع الدعوي الرقمي — الموازنة في لقاءات العمل الرسمية للمسلم الجديد',
        source_page_url: 'https://center.dawa.sa/item/business-dinner-balance',
        verbatim_evidence_text: 'إذا اضطر الموظف المسلم لحضور لقاء عمل مهني، وجب أن تكون طاولته المباشرة خالية تماماً من المسكرات، والاعتذار بلباقة واحترام يعزز مكانة المسلم ومبادئه.',
      },
    ],
    learning_criteria: {
      required_concepts: ['اجتناب مائدة الخمر المباشرة', 'التواصل المهني الهادئ والمحترم'],
      common_misconceptions: ['مداهنة الزملاء وشرب المحرم خجلاً', 'العدوانية والتشنج في التعبير عن المبدأ'],
    },
    related_scenarios: ['SCN_018', 'SCN_042'],
    related_city_experience: 'work-lunch-halal',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_020',
    numeric_id: 20,
    title_ar: 'العمل في متجر يبيع بعض المحرمات',
    title_en: 'Working in Retail Store Selling Mixed Permissible and Prohibited Goods',
    topic: 'social',
    unique_user_intent: 'social_retail_mixed_employment',
    contexts: ['store', 'supermarket', 'employment'],
    learning_objective_ar: 'تجنب المباشرة لبيع المحرم كالمسكرات ولحم الخنزير والبحث عن البديل الطيب',
    learning_objective_en: 'Avoid direct handling or selling of alcohol and pork while seeking better alternatives',
    difficulty: 'intermediate',
    interaction_engine: 'decision',
    keywords_ar: ['عمل بالسوبرماركت', 'بيع الدخان او الخمر', 'كاشير المحرمات'],
    keywords_en: ['cashier prohibited items', 'retail job', 'mixed commerce'],
    approved_sources: [],
    learning_criteria: {
      required_concepts: [],
      common_misconceptions: ['جواز المباشرة لبيع الخنزير والخمر لمجرد كونه عاملاً'],
    },
    related_scenarios: ['SCN_017', 'SCN_019'],
    related_city_experience: 'street-honesty-amanah',
    source_status: 'NEEDS_REVIEW',
    is_active: false,
  },
  {
    id: 'SCN_021',
    numeric_id: 21,
    title_ar: 'قصر وجمع الصلاة في السفر',
    title_en: 'Shortening and Combining Prayers in Travel',
    topic: 'travel',
    unique_user_intent: 'travel_prayer_shortening_combining',
    contexts: ['travel', 'highway', 'transit'],
    learning_objective_ar: 'قصر الصلاة الرباعية ركعتين والجمع تقديماً أو تأخيراً في مسافة السفر',
    learning_objective_en: 'Shorten four-rakah prayers to two, and combine Dhuhr/Asr or Maghrib/Isha during travel',
    difficulty: 'beginner',
    interaction_engine: 'sequence',
    keywords_ar: ['قصر الصلاة', 'جمع التقديم والتأخير', 'مسافة السفر', 'رخصة المسافر'],
    keywords_en: ['shortening prayer', 'combining salah', 'travel distance concession'],
    approved_sources: [],
    learning_criteria: {
      required_concepts: [],
      common_misconceptions: ['قصر صلاة المغرب أو الفجر', 'وجوب الجمع كلما قصر مع عدم الحاجة'],
    },
    related_scenarios: ['SCN_011', 'SCN_014', 'SCN_022'],
    related_city_experience: 'travel-concession',
    source_status: 'NEEDS_REVIEW',
    is_active: false,
  },
  {
    id: 'SCN_022',
    numeric_id: 22,
    title_ar: 'الجمع بين الصلاتين لعذر المطر الشديد والوحل',
    title_en: 'Combining Prayers Due to Heavy Rain and Flooded Streets',
    topic: 'prayer',
    unique_user_intent: 'prayer_combining_for_heavy_rain',
    contexts: ['mosque', 'rain', 'neighborhood'],
    learning_objective_ar: 'مشروعية جمع المغرب والعشاء أو الظهر والعصر لعذر المطر الشديد الناقع للثياب',
    learning_objective_en: 'Permissibility of combining prayers during torrential rain and flooding to prevent severe hardship',
    difficulty: 'beginner',
    interaction_engine: 'decision',
    keywords_ar: ['جمع المطر', 'وحل شديد', 'سيول', 'صلاة بالمطر'],
    keywords_en: ['rain concession', 'combining in rain', 'flooded streets'],
    approved_sources: [
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'صحيح البخاري — حديث ابن عباس في جمع النبي ﷺ بالمدينة من غير خوف ولا سفر',
        source_page_url: 'https://dorar.net/hadith/sharh/1297',
        verbatim_evidence_text: '«جمع رسول الله ﷺ بين الظهر والعصر، والمغرب والعشاء بالمدينة، في غير خوف ولا مطر.. قيل لابن عباس: لم فعل ذلك؟ قال: كي لا يحرج أمته»',
      },
      {
        registry_source_id: 'dorar_fiqh',
        reference_title: 'الموسوعة الفقهية — ضوابط الجمع لعذر المطر والوحل والريح الشديدة',
        source_page_url: 'https://dorar.net/feqhia/1168',
        verbatim_evidence_text: 'يجوز الجمع بين المغرب والعشاء تقديماً لعذر المطر الذي يبل الثياب وتلحق المشقة بالخروج فيه، وكذلك الوحل الشديد والبرد المؤذي.',
      },
    ],
    learning_criteria: {
      required_concepts: ['رفع الحرج والمشقة عن المصلين', 'ضابط المطر المبيح للجمع هو الذي يبل الثياب بمشقة'],
      common_misconceptions: ['الجمع للمطر الخفيف أو الرذاذ العابر', 'قصر الصلاة في الحضر للمطر (القصر خاص بالسفر)'],
    },
    related_scenarios: ['SCN_007', 'SCN_010', 'SCN_021'],
    related_city_experience: 'rain-concession',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_023',
    numeric_id: 23,
    title_ar: 'حيرة تغيير الاسم الأصلي بعد الإسلام',
    title_en: 'Keeping Original Birth Name After Embracing Islam',
    topic: 'social',
    unique_user_intent: 'social_birth_name_retention',
    contexts: ['family', 'passport', 'identity'],
    learning_objective_ar: 'جواز استبقاء الاسم الأصلي ما لم يكن معبداً لغير الله أو قبيح المعنى',
    learning_objective_en: 'Permissibility of keeping one’s original name unless meaning contradicts Tawhid or is derogatory',
    difficulty: 'beginner',
    interaction_engine: 'inspection',
    keywords_ar: ['تغيير الاسم', 'اسمي بعد الاسلام', 'الاسم الاصلي', 'تسمية اسلامية'],
    keywords_en: ['changing name in islam', 'keep birth name', 'islamic identity name'],
    approved_sources: [
      {
        registry_source_id: 'dawah_center',
        reference_title: 'المستودع الدعوي الرقمي — تأصيل مسألة أسماء المسلمين الجدد',
        source_page_url: 'https://center.dawa.sa/item/new-muslim-names',
        verbatim_evidence_text: 'لا يلزم المسلم الجديد تغيير اسمه الذي ولد به إلا إذا كان متضمناً عبودية لغير الله كعبد المسيح، أو معنى شنيعاً، والصحابة الكرام دخلوا في دين الله وبقوا على أسمائهم كعمر وعلي وسعد.',
      },
      {
        registry_source_id: 'jamhara_dict',
        reference_title: 'موسوعة مفردات المحتوى الإسلامي — معجم الأسماء والضوابط اللغوية',
        source_page_url: 'https://islamic-content.com/dictionary/naming-conventions',
        verbatim_evidence_text: 'الأصل في الأسماء الإباحة وجواز استبقاء الاسم الثقافي والوطني، مع وجوب انتساب الشخص لأبيه وأسرته لقوله تعالى ﴿ادْعُوهُمْ لِآبَائِهِمْ﴾.',
      },
    ],
    learning_criteria: {
      required_concepts: ['الأصل بقاء الأسماء على حالها', 'وجوب التغيير فقط للأسماء الشركية كعبد فلان لغير الله', 'حفظ النسب العائلي'],
      common_misconceptions: ['وجوب اختيار اسم عربي كشرط لصحة الإسلام', 'تغيير اسم العائلة بما يقطع صلة الرحم بالأبوين'],
    },
    related_scenarios: ['SCN_026', 'SCN_044', 'SCN_055'],
    related_city_experience: 'family-communication',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_024',
    numeric_id: 24,
    title_ar: 'خطأ جهة القبلة بالبوصلة الرقمية أو الاجتهاد',
    title_en: 'Qibla Direction Error Detected After Prayer',
    topic: 'prayer',
    unique_user_intent: 'prayer_qibla_error_after_salah',
    contexts: ['hotel', 'room', 'travel'],
    learning_objective_ar: 'صحة الصلاة الماضية بالاجتهاد وعدم وجوب إعادتها إن تبين الخطأ بعد الفراغ',
    learning_objective_en: 'Prayer performed with sincere estimation is valid; no obligation to repeat if discovered after completion',
    difficulty: 'beginner',
    interaction_engine: 'decision',
    keywords_ar: ['صليت لغير القبلة', 'خطأ اتجاه القبلة', 'البوصلة غلط'],
    keywords_en: ['wrong qibla', 'qibla compass error', 'salah facing wrong way'],
    approved_sources: [],
    learning_criteria: {
      required_concepts: [],
      common_misconceptions: ['وجوب قضاء كل الصلوات التي صلاها باجتهاد سابق'],
    },
    related_scenarios: ['SCN_011', 'SCN_013'],
    related_city_experience: 'home-prayer-room',
    source_status: 'NEEDS_REVIEW',
    is_active: false,
  },
  {
    id: 'SCN_025',
    numeric_id: 25,
    title_ar: 'مدة المسح على الخفين والجوربين للمسافر والمقيم',
    title_en: 'Duration of Wiping Over Socks and Footwear',
    topic: 'purity',
    unique_user_intent: 'purity_duration_wiping_socks',
    contexts: ['home', 'office', 'travel'],
    learning_objective_ar: 'المسح يوماً وليلة للمقيم وثلاثة أيام بلياليها للمسافر ابتداءً من أول مسح بعد الحدث',
    learning_objective_en: 'Wiping lasts 24 hours for resident and 72 hours for traveler starting from first wipe after invalidation',
    difficulty: 'beginner',
    interaction_engine: 'sequence',
    keywords_ar: ['مسح على الجوارب', 'مسح على الخفين', 'مدة المسح للمقيم', 'مدة المسح للمسافر'],
    keywords_en: ['wiping socks', 'khuffayn duration', 'resident vs traveler wiping'],
    approved_sources: [
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'صحيح مسلم — حديث علي بن أبي طالب رضي الله عنه في توقيت المسح',
        source_page_url: 'https://dorar.net/hadith/sharh/2689',
        verbatim_evidence_text: '«جعل رسول الله ﷺ ثلاثة أيام ولياليهن للمسافر، ويوما وليلة للمقيم»',
      },
      {
        registry_source_id: 'new_muslim_guide',
        reference_title: 'دليل المسلم الجديد — كيفية المسح على الجوارب وشروطه',
        source_page_url: 'https://www.newmuslimguide.com/ar/your-purification/wiping-over-socks',
        verbatim_evidence_text: 'يجوز المسح على الجوربين الساترين إذا لُبسا على طهارة كاملة، وتبدأ المدة من أول مسحة مسحها بعد انتقاض وضوئه.',
      },
    ],
    learning_criteria: {
      required_concepts: ['لبسهما على طهارة مائية كاملة', 'ابتداء حساب المدة من أول مسحة بعد الحدث', 'يوم وليلة للمقيم و3 أيام للمسافر'],
      common_misconceptions: ['حساب المدة من وقت اللبس وليس من وقت المسح', 'خلع الجورب يوجب الغسل الكامل'],
    },
    related_scenarios: ['SCN_006', 'SCN_010', 'SCN_014'],
    related_city_experience: 'home-prayer-room',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_026',
    numeric_id: 26,
    title_ar: 'ثقل ذنوب الماضي والخوف من عدم قبول التوبة',
    title_en: 'Past Sins Guilt and Assurance of Forgiveness in Islam',
    topic: 'mindset',
    unique_user_intent: 'mindset_past_sins_forgiveness_assurance',
    contexts: ['personal', 'heart', 'conversion'],
    learning_objective_ar: 'اليقين بأن الإسلام يجب ما قبله والتوبة الصادقة تمحو الخطايا',
    learning_objective_en: 'Firm certainty that embracing Islam eradicates past sins entirely and opens clean page',
    difficulty: 'beginner',
    interaction_engine: 'transfer',
    keywords_ar: ['ذنوب الماضي', 'توبة', 'الاسلام يجب ما قبله', 'خوف من الذنوب'],
    keywords_en: ['past sins', 'islam erases sins', 'repentance assurance', 'forgiveness'],
    approved_sources: [
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'صحيح مسلم — حديث عمرو بن العاص رضي الله عنه عند إسلامه',
        source_page_url: 'https://dorar.net/hadith/sharh/14389',
        verbatim_evidence_text: '«أما علمت يا عمرو أن الإسلام يهدم ما كان قبله، وأن الهجرة تهدم ما كان قبلها، وأن الحج يهدم ما كان قبله»',
      },
      {
        registry_source_id: 'quranpedia',
        reference_title: 'سورة الزمر: الآية 53 — سعة رحمة الله ومغفرة الذنوب جميعاً',
        source_page_url: 'https://quranpedia.net/surah/39/53',
        verbatim_evidence_text: '﴿قُلْ يَا عِبَادِيَ الَّذِينَ أَسْرَفُوا عَلَى أَنفُسِهِمْ لَا تَقْنَطُوا مِن رَّحْمَةِ اللَّهِ إِنَّ اللَّهَ يَغْفِرُ الذُّنُوبَ جَمِيعًا إِنَّهُ هُوَ الْغَفُورُ الرَّحِيمُ﴾',
      },
    ],
    learning_criteria: {
      required_concepts: ['الإسلام يجبّ ما كان قبله تماماً', 'رحمة الله تسع الذنوب جميعاً بالتوبة', 'عدم القنوط'],
      common_misconceptions: ['وجوب قضاء صلوات أو صيام السنين التي سبقت الإسلام'],
    },
    related_scenarios: ['SCN_005', 'SCN_023', 'SCN_060'],
    related_city_experience: 'home-prayer-room',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_027',
    numeric_id: 27,
    title_ar: 'مواجهة الخلاف الفقهي والتعصب المذهبي',
    title_en: 'Navigating Juristic Differences Without Partisanship',
    topic: 'mindset',
    unique_user_intent: 'mindset_fiqh_differences_etiquette',
    contexts: ['community', 'study_circle'],
    learning_objective_ar: 'فهم سعة الشريعة واحترام المذاهب المعتبرة دون تعصب أو تشاحن',
    learning_objective_en: 'Appreciate legitimate diversity of juristic schools without bigotry or division',
    difficulty: 'intermediate',
    interaction_engine: 'transfer',
    keywords_ar: ['خلاف فقهي', 'تعصب مذهبي', 'سعة الشريعة', 'اختلاف العلماء'],
    keywords_en: ['fiqh disagreement', 'madhhab differences', 'scholarly consensus'],
    approved_sources: [],
    learning_criteria: {
      required_concepts: [],
      common_misconceptions: ['اعتبار كل مسألة فرعية اجتهادية معركة حق وباطل'],
    },
    related_scenarios: ['SCN_028', 'SCN_057'],
    related_city_experience: 'first-row-mosque',
    source_status: 'NEEDS_REVIEW',
    is_active: false,
  },
  {
    id: 'SCN_028',
    numeric_id: 28,
    title_ar: 'الحرج من السؤال وتأخير البيان',
    title_en: 'Overcoming Hesitation to Ask Questions in Religion',
    topic: 'mindset',
    unique_user_intent: 'mindset_overcoming_question_hesitation',
    contexts: ['mosque', 'class', 'community'],
    learning_objective_ar: 'طرد الحياء المانع من التعلم وسؤال أهل الذكر بيقين وراحة قلب',
    learning_objective_en: 'Banish shyness preventing essential knowledge and ask scholars confidently',
    difficulty: 'beginner',
    interaction_engine: 'transfer',
    keywords_ar: ['حرج من السؤال', 'خجلان اسال', 'فاسالوا اهل الذكر', 'طلب العلم'],
    keywords_en: ['shyness in learning', 'hesitation to ask', 'seeking knowledge'],
    approved_sources: [
      {
        registry_source_id: 'quranpedia',
        reference_title: 'سورة النحل: الآية 43 — سؤال أهل العلم عند الجهل',
        source_page_url: 'https://quranpedia.net/surah/16/43',
        verbatim_evidence_text: '﴿فَاسْأَلُوا أَهْلَ الذِّكْرِ إِن كُنتُمْ لَا تَعْلَمُونَ﴾',
      },
      {
        registry_source_id: 'dorar_hadith',
        reference_title: 'صحيح البخاري تعليقاً — أثر عائشة رضي الله عنها في نساء الأنصار',
        source_page_url: 'https://dorar.net/hadith/sharh/129',
        verbatim_evidence_text: '«نعم النساء نساء الأنصار، لم يكن يمنعهن الحياء أن يتفقهن في الدين»',
      },
    ],
    learning_criteria: {
      required_concepts: ['الحياء الشرعي لا يمنع من طلب الحق', 'سؤال أهل الذكر الموثوقين المعتمدين'],
      common_misconceptions: ['البقاء في حيرة وشك خوفاً من لوم الناس'],
    },
    related_scenarios: ['SCN_026', 'SCN_027', 'SCN_057'],
    related_city_experience: 'family-communication',
    source_status: 'SOURCE_VALIDATED',
    is_active: true,
  },
  {
    id: 'SCN_029',
    numeric_id: 29,
    title_ar: 'صعوبة حفظ الفاتحة وقراءة الصلاة في البداية',
    title_en: 'Initial Difficulty Memorizing Surah Al-Fatihah',
    topic: 'prayer',
    unique_user_intent: 'prayer_initial_fatihah_memorization',
    contexts: ['home', 'prayer_room'],
    learning_objective_ar: 'التدرج بالأذكار البديلة (سبحان الله والحمد لله) حتى يتمكن من حفظ الفاتحة',
    learning_objective_en: 'Step-by-step substitution with basic remembrance until Fatihah is memorized',
    difficulty: 'beginner',
    interaction_engine: 'sequence',
    keywords_ar: ['صعوبة حفظ الفاتحة', 'مش حافظ الفاتحة', 'بديل الفاتحة للجديد'],
    keywords_en: ['cannot read fatihah', 'memorize fatihah struggle', 'beginner prayer substitute'],
    approved_sources: [],
    learning_criteria: {
      required_concepts: [],
      common_misconceptions: ['ترك الصلاة بالكامل حتى يتقن حفظ الفاتحة غيباً'],
    },
    related_scenarios: ['SCN_001', 'SCN_028'],
    related_city_experience: 'home-prayer-room',
    source_status: 'NEEDS_REVIEW',
    is_active: false,
  },
  {
    id: 'SCN_030',
    numeric_id: 30,
    title_ar: 'حساب وإخراج زكاة الفطر بالأرز أو الحبوب',
    title_en: 'Calculating and Paying Zakat al-Fitr in Rice or Grain',
    topic: 'social',
    unique_user_intent: 'social_zakat_al_fitr_calculation',
    contexts: ['market', 'home', 'ramadan'],
    learning_objective_ar: 'إخراج صاع من غالب قوت البلد (كالطعام أو الأرز نحو 2.5 كجم) قبل صلاة العيد',
    learning_objective_en: 'Distribute one Sa\'a of staple food (approx 2.5 kg rice) to the needy before Eid prayer',
    difficulty: 'beginner',
    interaction_engine: 'inspection',
    keywords_ar: ['زكاة الفطر', 'صاع رز', 'كيلو رز زكاة', 'موعد زكاة الفطر'],
    keywords_en: ['zakat al fitr', 'saa of rice', 'fitr calculation', 'eid charity'],
    approved_sources: [],
    learning_criteria: {
      required_concepts: [],
      common_misconceptions: ['تأخير زكاة الفطر إلى ما بعد صلاة العيد بلا عذر'],
    },
    related_scenarios: ['SCN_017', 'SCN_059'],
    related_city_experience: 'market-amanah',
    source_status: 'NEEDS_REVIEW',
    is_active: false,
  },
];
